---
sidebar: modules
---

# M1A: Install R and RStudio

This content draws on material from [STAT 545](https://stat545.com/) by [Jenny Bryan](https://jennybryan.org/), licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)

Changes to the source material include addition of new material; light editing; rearranging, removing, and combining original material; adding and changing links; and adapting the language for the current course.

The resulting content is licensed under [CC BY-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/).

## Introduction

Learning data science involves more than memorizing facts. One sociocultural view of learning assumes that:

> knowledge is distributed in the world among individuals, the tools, artifacts, and books that they use, and the communities and practices in which they participate (Greeno et al., 1996, p. 20)

From this perspective, learning data science involves becoming familiar with data science communities, using the tools that data scientists use, and practicing the ways that data scientists work.

In relation to this second point, R and RStudio are widely used software tools in data science, so becoming familiar with them is part of learning data science. Other software can also be used for data science; this course uses R and RStudio.

This activity is about introducing you to this software and helping you set it up. Even if you have a pre-existing installation of R or RStudio, re-installing both and using current versions is strongly recommended. It can be considerably harder to run old software than new.

## R

[R](https://www.r-project.org/) is an open source programming language designed for statistics. Two things are important about that initial description:

First, R is *open source*, meaning that is freely available and that other programmers may add to it or modify it to their heart's content. This is good news—it means that in addition to the basic features of R, it is possible (and relatively easy) to add new features by installing and loading *packages*. The course will use many such packages.

Second, R is *designed for statistics*. That doesn't mean it can't be used for other things; R can also be used for purposes other than traditional statistics. Nonetheless, R is built with statistical needs and tasks in mind.

You should now install R from [CRAN](https://cloud.r-project.org/), the Comprehensive R Archive Network. Install a precompiled binary distribution for your operating system rather than the source code. Follow the link for your operating system at the CRAN link in this paragraph.

## RStudio

Programming in R can be done in a number of ways, but this course uses an IDE (*[integrated development environment](https://en.wikipedia.org/wiki/Integrated_development_environment)*) called RStudio (developed by an organization called Posit).

To download RStudio Desktop, navigate to this [this link](https://posit.co/download/rstudio-desktop/). It will provide you with a link for downloading R; since you've already done that, you can ignore it. Download the RStudio version for your computer's operating system.

It's important to understand that RStudio is one of many interfaces available for working with the R programming language. Another interface (simply called R) will also be installed on your computer as a result of installing the R language, and it will be possible to open R code in either the R interface or the RStudio interface. Use RStudio when working with code for this course. RStudio provides extra features that will be used throughout the semester.

## References

Greeno, J., Collins, A., & Resnick, L. (1996). Cognition and learning. In D. Berliner & R. Calfee (eds.), *Handbook of educational psychology* (pp. 15-46). Macmillan.
