<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>18&nbsp; M6A: Wrangling and Tidying Data – Introduction to Data Science</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./18_module_6_connection.html" rel="next">
<link href="./16_module_6_understanding.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./17_module_6_application.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">M6A: Wrangling and Tidying Data</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Data Science</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to Data Science</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_module_1_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">M1U: Course Syllabus</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_module_1_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">M1A: Install R and RStudio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_module_1_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">M1C: Introduce Yourself to the Class</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_module_2_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">M2U: The New(?) and Shiny(?) Science of Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_module_2_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">M2A: Getting Started with Data in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_module_2_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">M2C: Set up GitHub</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_module_3_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">M3U: Research Paradigms and Reproducibility</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_module_3_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">M3A: Using Projects and Scripts in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_module_3_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">M3C: Writing in R Markdown</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_module_4_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">M4U: The Value of Open Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_module_4_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">M4A: Find a Dataset Relevant To You</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12_module_4_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">M4C: Show Your Work</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13_module_5_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">M5U: Numbers Don’t Speak for Themselves</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14_module_5_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">M5A: Are Ethics Enough in Data Science?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15_module_5_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">M5C: Reflect on Theoretical and Philosophical Constraints</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16_module_6_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">M6U: Unicorns, Janitors, and Rock Stars</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17_module_6_application.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">M6A: Wrangling and Tidying Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18_module_6_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">M6C: Practice Wrangling and Tidying Your Own Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19_module_7_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">M7U: Subjectivity in Data Visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20_module_7_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">M7A: Data Visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21_module_7_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">M7C: Practice Visualizing Your Own Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22_module_8_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">M8U: Statistics and Scientific Racism</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23_module_8_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">M8A: Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24_module_8_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">M8C: Calculate Descriptive Statistics for Your Own Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25_module_9_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">M9U: Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./26_module_9_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">M9A: Basic Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./27_module_9_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">M9C: Perform a Basic Regression With Your Own Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./28_module_10_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">M10U: Consequences of Failed Predictions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./29_module_10_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">M10A: Multiple Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./30_module_10_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">M10C: Perform a Multiple Regression With Your Own Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./31_module_11_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">M11U: Samples and Populations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./32_module_11_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">M11A: Sampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./33_module_11_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">M11C: Explore Sampling With Your Own Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./34_module_12_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">M12U: Confident About What?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./35_module_12_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">M12A: Confidence Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./36_module_12_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">M12C: Explore Confidence Intervals With Your Own Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./37_module_13_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">M13U: The Dangers of False Positives</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./38_module_13_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">M13: Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./39_module_13_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">M13C: Explore Hypothesis Testing With Your Own Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./40_module_14_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">M14U: Small Stories vs.&nbsp;Big Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./41_module_14_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">M14A: Inferential Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./42_module_14_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">M14C: Perform an Inferential Regression With Your Own Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./43_module_15_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">M15U: Reflect on Your Understanding of Data Science</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./44_module_15_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">M15A: Reflect on Your Application of Data Science</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./45_module_15_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">M15C: Reflect on Your Connection of Data Science</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">18.1</span> Introduction</a></li>
  <li><a href="#wrangling" id="toc-wrangling" class="nav-link" data-scroll-target="#wrangling"><span class="header-section-number">18.2</span> Wrangling</a>
  <ul class="collapse">
  <li><a href="#sec-wrangling-packages" id="toc-sec-wrangling-packages" class="nav-link" data-scroll-target="#sec-wrangling-packages">Needed packages</a></li>
  <li><a href="#sec-piping" id="toc-sec-piping" class="nav-link" data-scroll-target="#sec-piping"><span class="header-section-number">18.2.1</span> The pipe operator: <code>|&gt;</code></a></li>
  <li><a href="#sec-filter" id="toc-sec-filter" class="nav-link" data-scroll-target="#sec-filter"><span class="header-section-number">18.2.2</span> <code>filter</code> rows</a></li>
  <li><a href="#sec-mutate" id="toc-sec-mutate" class="nav-link" data-scroll-target="#sec-mutate"><span class="header-section-number">18.2.3</span> <code>mutate</code> existing variables</a></li>
  <li><a href="#sec-arrange" id="toc-sec-arrange" class="nav-link" data-scroll-target="#sec-arrange"><span class="header-section-number">18.2.4</span> <code>arrange</code> and sort rows</a></li>
  <li><a href="#sec-joins" id="toc-sec-joins" class="nav-link" data-scroll-target="#sec-joins"><span class="header-section-number">18.2.5</span> <code>join</code> data frames</a></li>
  <li><a href="#sec-normal-forms" id="toc-sec-normal-forms" class="nav-link" data-scroll-target="#sec-normal-forms"><span class="header-section-number">18.2.6</span> Normal forms</a></li>
  <li><a href="#sec-other-verbs" id="toc-sec-other-verbs" class="nav-link" data-scroll-target="#sec-other-verbs"><span class="header-section-number">18.2.7</span> Other verbs</a></li>
  <li><a href="#top_n-values-of-a-variable" id="toc-top_n-values-of-a-variable" class="nav-link" data-scroll-target="#top_n-values-of-a-variable"><span class="header-section-number">18.2.8</span> <code>top_n</code> values of a variable</a></li>
  </ul></li>
  <li><a href="#tidying-data" id="toc-tidying-data" class="nav-link" data-scroll-target="#tidying-data"><span class="header-section-number">18.3</span> Tidying Data</a>
  <ul class="collapse">
  <li><a href="#sec-tidy-packages" id="toc-sec-tidy-packages" class="nav-link" data-scroll-target="#sec-tidy-packages">Needed packages</a></li>
  <li><a href="#sec-csv" id="toc-sec-csv" class="nav-link" data-scroll-target="#sec-csv"><span class="header-section-number">18.3.1</span> Importing data</a></li>
  <li><a href="#sec-tidy-data-ex" id="toc-sec-tidy-data-ex" class="nav-link" data-scroll-target="#sec-tidy-data-ex"><span class="header-section-number">18.3.2</span> “Tidy” data</a></li>
  <li><a href="#sec-tidy-definition" id="toc-sec-tidy-definition" class="nav-link" data-scroll-target="#sec-tidy-definition"><span class="header-section-number">18.3.3</span> Definition of “tidy” data</a></li>
  <li><a href="#converting-to-tidy-data" id="toc-converting-to-tidy-data" class="nav-link" data-scroll-target="#converting-to-tidy-data"><span class="header-section-number">18.3.4</span> Converting to “tidy” data</a></li>
  <li><a href="#sec-case-study-tidy" id="toc-sec-case-study-tidy" class="nav-link" data-scroll-target="#sec-case-study-tidy"><span class="header-section-number">18.3.5</span> Case study: Democracy in Guatemala</a></li>
  </ul></li>
  <li><a href="#sec-tidyverse-package" id="toc-sec-tidyverse-package" class="nav-link" data-scroll-target="#sec-tidyverse-package"><span class="header-section-number">18.4</span> <code>tidyverse</code> package</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">18.5</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-wrangling" class="quarto-section-identifier"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">M6A: Wrangling and Tidying Data</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This content draws on material from <em><a href="https://moderndive.com/v2">Statistical Inference via Data Science: A ModernDive into R and the Tidyverse [Second Edition]</a></em> by <a href="https://chester.rbind.io/">Chester Ismay</a>, <a href="https://rudeboybert.rbind.io/">Albert Y. Kim</a>, and <a href="https://avaldivi6.github.io/">Arturo Valdivia</a> licensed under <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a></p>
<p>Changes to the source material include addition of new material; light editing; rearranging, removing, and combining original material; adding and changing links; and adding first-person language from current author.</p>
<p>The resulting content is licensed under <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>.</p>
<section id="introduction" class="level2" data-number="18.1">
<h2 data-number="18.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">18.1</span> Introduction</h2>
<p>Two weeks ago, we learned about importing a dataset into R. However, sometimes the dataset that we’ve found isn’t precisely the data that we need. In this walkthrough, we’ll practice <em>wrangling</em> data and <em>tidying</em> data—two skills that help us transform the data we have into the data we want.</p>
</section>
<section id="wrangling" class="level2" data-number="18.2">
<h2 data-number="18.2" class="anchored" data-anchor-id="wrangling"><span class="header-section-number">18.2</span> Wrangling</h2>
<p>In this section, we’ll cover a series of functions from the <code>dplyr</code> package for data wrangling that will allow you to take a data frame and “wrangle” it (transform it) to suit your needs. Such functions include:</p>
<ol type="1">
<li><code>filter()</code> a data frame’s existing rows to only pick out a subset of them.</li>
<li><code>mutate()</code> its existing columns/variables to create new ones. For example, convert hourly temperature recordings from degrees Fahrenheit to degrees Celsius.</li>
<li><code>arrange()</code> its rows. For example, sort rows of a dataframe in ascending or descending order of a particular variable.</li>
<li><code>join()</code> it with another data frame by matching along a “key” variable. In other words, merge these two data frames together.</li>
</ol>
<p>Notice how I’ve used <code>computer_code</code> font to describe the actions we want to take on our data frames. This is because the <code>dplyr</code> package for data wrangling has intuitively verb-named functions that are easy to remember.</p>
<p>There is a further benefit to learning to use the <code>dplyr</code> package for data wrangling: its similarity to the database querying language <a href="https://en.wikipedia.org/wiki/SQL">SQL</a> (pronounced “sequel” or spelled out as “S”, “Q”, “L”). SQL (which stands for “Structured Query Language”) is used to manage large databases quickly and efficiently and is widely used by many institutions with a lot of data. While SQL is a topic left for a book or a course on database management, keep in mind that once you learn <code>dplyr</code>, you can learn SQL more easily.</p>
<section id="sec-wrangling-packages" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="sec-wrangling-packages">Needed packages</h3>
<p>Let’s load all the packages needed for our wrangling practice (this assumes you’ve already installed them). If needed, read Section <a href="05_module_2_application.html#sec-packages" class="quarto-xref"><span>Section 6.3</span></a> for information on how to install and load R packages.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nycflights23)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="sec-piping" class="level3" data-number="18.2.1">
<h3 data-number="18.2.1" class="anchored" data-anchor-id="sec-piping"><span class="header-section-number">18.2.1</span> The pipe operator: <code>|&gt;</code></h3>
<p>Before we start data wrangling, let’s first introduce a nifty tool that has been a part of R since May 2021: the native pipe operator <code>|&gt;</code>. The pipe operator allows us to combine multiple operations in R into a single sequential <em>chain</em> of actions. In modern R, the native pipe operator <code>|&gt;</code> is now the default for chaining functions, replacing the previously common tidyverse pipe (<code>%&gt;%</code>) that was loaded with the <code>dplyr</code> package. Introduced in R 4.1.0 in May 2021, <code>|&gt;</code> offers a more intuitive and readable syntax for data wrangling and other tasks, eliminating the need for additional package dependencies.</p>
<p>You’ll still often see R code using <code>%&gt;%</code> in older scripts or searches online, but we’ll use <code>|&gt;</code> in this class. The tidyverse pipe still works, so don’t worry if you see it in other code.</p>
<p>Let’s start with a hypothetical example. Say you would like to perform a hypothetical sequence of operations on a hypothetical data frame <code>x</code> using hypothetical functions <code>f()</code>, <code>g()</code>, and <code>h()</code>:</p>
<ol type="1">
<li>Take <code>x</code> <em>then</em></li>
<li>Use <code>x</code> as an input to a function <code>f()</code> <em>then</em></li>
<li>Use the output of <code>f(x)</code> as an input to a function <code>g()</code> <em>then</em></li>
<li>Use the output of <code>g(f(x))</code> as an input to a function <code>h()</code></li>
</ol>
<p>One way to achieve this sequence of operations is by using nesting parentheses as follows:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">h</span>(<span class="fu">g</span>(<span class="fu">f</span>(x)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This code isn’t so hard to read since we are applying only three functions: <code>f()</code>, then <code>g()</code>, then <code>h()</code> and each of the functions is short in its name. Further, each of these functions also only has one argument. However, you can imagine that this will get progressively harder to read as the number of functions applied in your sequence increases and the arguments in each function increase as well. This is where the pipe operator <code>|&gt;</code> comes in handy. <code>|&gt;</code> takes the output of one function and then “pipes” it to be the input of the next function. Furthermore, a helpful trick is to read <code>|&gt;</code> as “then” or “and then.” For example, you can obtain the same output as the hypothetical sequence of functions as follows:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">|&gt;</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">f</span>() <span class="sc">|&gt;</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">g</span>() <span class="sc">|&gt;</span> </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">h</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>You would read this sequence as:</p>
<ol type="1">
<li>Take <code>x</code> <em>then</em></li>
<li>Use this output as the input to the next function <code>f()</code> <em>then</em></li>
<li>Use this output as the input to the next function <code>g()</code> <em>then</em></li>
<li>Use this output as the input to the next function <code>h()</code></li>
</ol>
<p>So while both approaches achieve the same goal, the latter is much more human-readable because you can clearly read the sequence of operations line-by-line. But what are the hypothetical <code>x</code>, <code>f()</code>, <code>g()</code>, and <code>h()</code>? Throughout this chapter on data wrangling:</p>
<ol type="1">
<li>The starting value <code>x</code> will be a data frame. For example, the <code>flights</code> data frame we explored in Section <a href="05_module_2_application.html#sec-nycflights" class="quarto-xref"><span>Section 6.4</span></a>.</li>
<li>The sequence of functions, here <code>f()</code>, <code>g()</code>, and <code>h()</code>, will mostly be a sequence of any number of the six data-wrangling verb-named functions we listed in the introduction to this chapter. For example, the <code>filter(carrier == "MQ")</code> function and argument specified we previewed earlier.</li>
<li>The result will be the transformed/modified data frame that you want. In our example, we’ll save the result in a new data frame by using the <code>&lt;-</code> assignment operator with the name <code>alaska_flights</code> via <code>alaska_flights &lt;-</code>.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>envoy_flights <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(carrier <span class="sc">==</span> <span class="st">"AS"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Keep in mind, there are many more advanced data-wrangling functions than just the six listed in the introduction to this chapter; you’ll see some examples of these in Section <a href="#sec-other-verbs" class="quarto-xref"><span>Section 18.2.7</span></a>. However, just with these six verb-named functions you’ll be able to perform a broad array of data-wrangling tasks for the rest of this book.</p>
</section>
<section id="sec-filter" class="level3" data-number="18.2.2">
<h3 data-number="18.2.2" class="anchored" data-anchor-id="sec-filter"><span class="header-section-number">18.2.2</span> <code>filter</code> rows</h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-filter" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-filter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/cheatsheets/filter.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-filter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18.1: Diagram of filter() rows operation.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The <code>filter()</code> function here works much like the “Filter” option in Microsoft Excel; it allows you to specify criteria about the values of a variable in your dataset and then filters out only the rows that match that criteria.</p>
<p>We begin by focusing only on flights from New York City to Phoenix, Arizona. The <code>dest</code> destination code (or airport code) for Phoenix, Arizona is <code>"PHX"</code>. Run the following and look at the results in RStudio’s spreadsheet viewer to ensure that only flights heading to Phoenix are chosen here:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>phoenix_flights <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(dest <span class="sc">==</span> <span class="st">"PHX"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(phoenix_flights)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Note the order of the code. First, take the <code>flights</code> data frame <code>flights</code> <em>then</em> <code>filter()</code> the data frame so that only those where the <code>dest</code> equals <code>"PHX"</code> are included. We test for equality using the double equal sign <code>==</code> and not a single equal sign <code>=</code>. In other words, <code>filter(dest = "PHX")</code> will yield an error. This is a convention across many programming languages. If you are new to coding, you’ll probably forget to use the double equal sign <code>==</code> a few times before you get the hang of it.</p>
<p>You can use other operators beyond just the <code>==</code> operator that tests for equality:</p>
<ul>
<li><code>&gt;</code> corresponds to “greater than”</li>
<li><code>&lt;</code> corresponds to “less than”</li>
<li><code>&gt;=</code> corresponds to “greater than or equal to”</li>
<li><code>&lt;=</code> corresponds to “less than or equal to”</li>
<li><code>!=</code> corresponds to “not equal to.” The <code>!</code> is used in many programming languages to indicate “not.”</li>
</ul>
<p>Furthermore, you can combine multiple criteria using operators that make comparisons:</p>
<ul>
<li><code>|</code> corresponds to “or”</li>
<li><code>&amp;</code> corresponds to “and”</li>
</ul>
<p>To see many of these in action, let’s filter <code>flights</code> for all rows that departed from JFK <em>and</em> were heading to Burlington, Vermont (<code>"BTV"</code>) or Seattle, Washington (<code>"SEA"</code>) <em>and</em> departed in the months of October, November, or December. Run the following:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>btv_sea_flights_fall <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(origin <span class="sc">==</span> <span class="st">"JFK"</span> <span class="sc">&amp;</span> (dest <span class="sc">==</span> <span class="st">"BTV"</span> <span class="sc">|</span> dest <span class="sc">==</span> <span class="st">"SEA"</span>) <span class="sc">&amp;</span> month <span class="sc">&gt;=</span> <span class="dv">10</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(btv_sea_flights_fall)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Note that even though colloquially speaking one might say “all flights leaving Burlington, Vermont <em>and</em> Seattle, Washington,” in terms of computer operations, we really mean “all flights leaving Burlington, Vermont <em>or</em> leaving Seattle, Washington.” For a given row in the data, <code>dest</code> can be <code>"BTV"</code>, or <code>"SEA"</code>, or something else, but not both <code>"BTV"</code> and <code>"SEA"</code> at the same time. Furthermore, note the careful use of parentheses around <code>dest == "BTV" | dest == "SEA"</code>.</p>
<p>We can often skip the use of <code>&amp;</code> and just separate our conditions with a comma. The previous code will return the identical output <code>btv_sea_flights_fall</code> as the following code:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>btv_sea_flights_fall <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(origin <span class="sc">==</span> <span class="st">"JFK"</span>, (dest <span class="sc">==</span> <span class="st">"BTV"</span> <span class="sc">|</span> dest <span class="sc">==</span> <span class="st">"SEA"</span>), month <span class="sc">&gt;=</span> <span class="dv">10</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(btv_sea_flights_fall)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Let’s present another example that uses the <code>!</code> “not” operator to pick rows that <em>don’t</em> match a criteria. As mentioned earlier, the <code>!</code> can be read as “not.” Here we are filtering rows corresponding to flights that didn’t go to Burlington, VT or Seattle, WA.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>not_BTV_SEA <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>(dest <span class="sc">==</span> <span class="st">"BTV"</span> <span class="sc">|</span> dest <span class="sc">==</span> <span class="st">"SEA"</span>))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(not_BTV_SEA)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Again, note the careful use of parentheses around the <code>(dest == "BTV" | dest == "SEA")</code>. If we didn’t use parentheses as follows:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>flights <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="sc">!</span>dest <span class="sc">==</span> <span class="st">"BTV"</span> <span class="sc">|</span> dest <span class="sc">==</span> <span class="st">"SEA"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We would be returning all flights not headed to <code>"BTV"</code> <em>or</em> those headed to <code>"SEA"</code>, which is an entirely different resulting data frame.</p>
<p>Now say we have a larger number of airports we want to filter for, say <code>"SEA"</code>, <code>"SFO"</code>, <code>"PHX"</code>, <code>"BTV"</code>, and <code>"BDL"</code>. We could continue to use the <code>|</code> (<em>or</em>) operator.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>many_airports <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(dest <span class="sc">==</span> <span class="st">"SEA"</span> <span class="sc">|</span> dest <span class="sc">==</span> <span class="st">"SFO"</span> <span class="sc">|</span> dest <span class="sc">==</span> <span class="st">"PHX"</span> <span class="sc">|</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>         dest <span class="sc">==</span> <span class="st">"BTV"</span> <span class="sc">|</span> dest <span class="sc">==</span> <span class="st">"BDL"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>As we progressively include more airports, this will get unwieldy to write. A slightly shorter approach uses the <code>%in%</code> operator along with the <code>c()</code> function. Recall from Subsection <a href="05_module_2_application.html#sec-programming-concepts" class="quarto-xref"><span>Section 6.2.1</span></a> that the <code>c()</code> function “combines” or “concatenates” values into a single <em>vector</em> of values. </p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>many_airports <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(dest <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"SEA"</span>, <span class="st">"SFO"</span>, <span class="st">"PHX"</span>, <span class="st">"BTV"</span>, <span class="st">"BDL"</span>))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(many_airports)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>What this code is doing is filtering <code>flights</code> for all flights where <code>dest</code> is in the vector of airports <code>c("BTV", "SEA", "PHX", "SFO", "BDL")</code>. Both outputs of <code>many_airports</code> are the same, but as you can see the latter takes much less energy to code. The <code>%in%</code> operator is useful for looking for matches commonly in one vector/variable compared to another.</p>
<p>As a final note, I recommend that <code>filter()</code> should often be among the first verbs you consider applying to your data. This cleans your dataset to only those rows you care about; put differently, it narrows down the scope of your data frame to just the observations you care about.</p>
</section>
<section id="sec-mutate" class="level3" data-number="18.2.3">
<h3 data-number="18.2.3" class="anchored" data-anchor-id="sec-mutate"><span class="header-section-number">18.2.3</span> <code>mutate</code> existing variables</h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mutatevars" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mutatevars-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/cheatsheets/mutate.png" class="img-fluid figure-img" style="width:40.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mutatevars-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18.2: Diagram of mutate() columns.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Another common transformation of data is to create/compute new variables based on existing ones as shown in Figure <a href="#fig-mutatevars" class="quarto-xref">Figure&nbsp;<span>18.2</span></a>. For example, say you are more comfortable thinking of temperature in degrees Celsius (°C) instead of degrees Fahrenheit (°F). The formula to convert temperatures from °F to °C is</p>
<p><span class="math display">\[
\text{temp in C} = \frac{\text{temp in F} - 32}{1.8}
\]</span></p>
<p>We can apply this formula to the <code>temp</code> variable using the <code>mutate()</code> function from the <code>dplyr</code> package, which takes existing variables and mutates them to create new ones.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>weather <span class="ot">&lt;-</span> weather <span class="sc">|&gt;</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">temp_in_C =</span> (temp <span class="sc">-</span> <span class="dv">32</span>) <span class="sc">/</span> <span class="fl">1.8</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>In this code, we <code>mutate()</code> the <code>weather</code> data frame by creating a new variable</p>
<p><code>temp_in_C = (temp - 32) / 1.8</code>,</p>
<p>and then we <em>overwrite</em> the original <code>weather</code> data frame. Why did we overwrite the data frame <code>weather</code>, instead of assigning the result to a new data frame like <code>weather_new</code>?</p>
<p>As a rough rule of thumb, as long as you are not losing original information that you might need later, it’s acceptable practice to overwrite existing data frames with updated ones, as we did here. On the other hand, why did we not overwrite the variable <code>temp</code>, but instead created a new variable called <code>temp_in_C</code>? Because if we did this, we would have erased the original information contained in <code>temp</code> of temperatures in Fahrenheit that may still be valuable to us.</p>
<p>Let’s consider another example. Passengers are often frustrated when their flight departs late, but aren’t as annoyed if, in the end, pilots can make up some time during the flight. This is known in the airline industry as <em>gain</em>, and we will create this variable using the <code>mutate()</code> function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>flights <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gain =</span> dep_delay <span class="sc">-</span> arr_delay)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Let’s take a look at only the <code>dep_delay</code>, <code>arr_delay</code>, and the resulting <code>gain</code> variables for the first 5 rows in our updated <code>flights</code> data frame in Table <a href="#tbl-first-five-flights" class="quarto-xref">Table&nbsp;<span>18.1</span></a>.</p>
<div class="cell">
<div id="tbl-first-five-flights" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-first-five-flights-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;18.1: First five rows of departure/arrival delay and gain variables
</figcaption>
<div aria-describedby="tbl-first-five-flights-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">dep_delay</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">arr_delay</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">gain</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">203</td>
<td style="text-align: right;">205</td>
<td style="text-align: right;">-2</td>
</tr>
<tr class="even">
<td style="text-align: right;">78</td>
<td style="text-align: right;">53</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="odd">
<td style="text-align: right;">47</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">13</td>
</tr>
<tr class="even">
<td style="text-align: right;">173</td>
<td style="text-align: right;">166</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: right;">228</td>
<td style="text-align: right;">211</td>
<td style="text-align: right;">17</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The flight in the first row departed 203 minutes late but arrived 205 minutes late, so its “gained time in the air” is a gain of -2 minutes, hence its <code>gain</code> is <span class="math inline">\(203 - 205 = -2\)</span>, which is a <code>loss</code> of 2 minutes. On the other hand, the flight in the third row departed late (<code>dep_delay</code> of 47) but arrived 34 minutes late (<code>arr_delay</code> of 34), so its “gained time in the air” is <span class="math inline">\(47 - 34 = 13\)</span> minutes, hence its <code>gain</code> is 13.</p>
<p>To close out our discussion on the <code>mutate()</code> function to create new variables, note that we can create multiple new variables at once in the same <code>mutate()</code> code. Furthermore, within the same <code>mutate()</code> code we can refer to new variables we just created. As an example, consider the <code>mutate()</code> code Hadley Wickham and Garrett Grolemund show in Chapter 5 of <em>R for Data Science</em> <span class="citation" data-cites="rds2016">[@rds2016]</span>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>flights <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">gain =</span> dep_delay <span class="sc">-</span> arr_delay,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">hours =</span> air_time <span class="sc">/</span> <span class="dv">60</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">gain_per_hour =</span> gain <span class="sc">/</span> hours</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="sec-arrange" class="level3" data-number="18.2.4">
<h3 data-number="18.2.4" class="anchored" data-anchor-id="sec-arrange"><span class="header-section-number">18.2.4</span> <code>arrange</code> and sort rows</h3>
<p>One of the most commonly performed data-wrangling tasks is to sort a data frame’s rows in the alphanumeric order of one of the variables. The <code>dplyr</code> package’s <code>arrange()</code> function allows us to sort/reorder a data frame’s rows according to the values of the specified variable.</p>
<p>Suppose we are interested in determining the most frequent destination airports for all domestic flights departing from New York City in 2023. To do this requires using the <code>group_by()</code> function, which we won’t cover in detail until later, but you should be able to get a sense for what it does and how it fits into everything else here.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>freq_dest <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(dest) <span class="sc">|&gt;</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">num_flights =</span> <span class="fu">n</span>())</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>freq_dest</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 118 × 2
   dest  num_flights
   &lt;chr&gt;       &lt;int&gt;
 1 ABQ           228
 2 ACK           916
 3 AGS            20
 4 ALB          1581
 5 ANC            95
 6 ATL         17570
 7 AUS          4848
 8 AVL          1617
 9 AVP           145
10 BDL           701
# ℹ 108 more rows</code></pre>
</div>
</div>
<p>Observe that by default the rows of the resulting <code>freq_dest</code> data frame are sorted in alphabetical order of <code>dest</code>ination. Say instead we would like to see the same data, but sorted from the most to the least number of flights (<code>num_flights</code>) instead:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>freq_dest <span class="sc">|&gt;</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(num_flights)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 118 × 2
   dest  num_flights
   &lt;chr&gt;       &lt;int&gt;
 1 LEX             1
 2 AGS            20
 3 OGG            20
 4 SBN            24
 5 HDN            28
 6 PNS            71
 7 MTJ            77
 8 ANC            95
 9 VPS           109
10 AVP           145
# ℹ 108 more rows</code></pre>
</div>
</div>
<p>This is, however, the opposite of what we want. The rows are sorted with the least frequent destination airports displayed first. This is because <code>arrange()</code> always returns rows sorted in ascending order by default. To switch the ordering to be in “descending” order instead, we use the <code>desc()</code> function as so:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>freq_dest <span class="sc">|&gt;</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(num_flights))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 118 × 2
   dest  num_flights
   &lt;chr&gt;       &lt;int&gt;
 1 BOS         19036
 2 ORD         18200
 3 MCO         17756
 4 ATL         17570
 5 MIA         16076
 6 LAX         15968
 7 FLL         14239
 8 CLT         12866
 9 DFW         11675
10 SFO         11651
# ℹ 108 more rows</code></pre>
</div>
</div>
</section>
<section id="sec-joins" class="level3" data-number="18.2.5">
<h3 data-number="18.2.5" class="anchored" data-anchor-id="sec-joins"><span class="header-section-number">18.2.5</span> <code>join</code> data frames</h3>
<p>Another common data transformation task is “joining” or “merging” two different datasets. For example, in the <code>flights</code> data frame, the variable <code>carrier</code> lists the carrier code for the different flights. While the corresponding airline names for <code>"UA"</code> and <code>"AA"</code> might be somewhat easy to guess (United and American Airlines), what airlines have codes <code>"VX"</code>, <code>"HA"</code>, and <code>"B6"</code>? This information is provided in a separate data frame <code>airlines</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(airlines)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We see that in <code>airlines</code>, <code>carrier</code> is the carrier code, while <code>name</code> is the full name of the airline company. Using this table, we can see that <code>"G4"</code>, <code>"HA"</code>, and <code>"B6"</code> correspond to Allegiant Air, Hawaiian Airlines, and JetBlue, respectively. However, wouldn’t it be nice to have all this information in a single data frame instead of two separate data frames? We can do this by “joining” the <code>flights</code> and <code>airlines</code> data frames.</p>
<p>The values in the variable <code>carrier</code> in the <code>flights</code> data frame match the values in the variable <code>carrier</code> in the <code>airlines</code> data frame. In this case, we can use the variable <code>carrier</code> as a <em>key variable</em> to match the rows of the two data frames. Key variables are almost always <em>identification variables</em> that uniquely identify the observational units as we saw in Subsection <a href="05_module_2_application.html#sec-identification-vs-measurement-variables" class="quarto-xref"><span>Section 6.4.4</span></a>. This ensures that rows in both data frames are appropriately matched during the join. Hadley and Garrett <span class="citation" data-cites="rds2016">[@rds2016]</span> created the diagram in Figure <a href="#fig-reldiagram" class="quarto-xref">Figure&nbsp;<span>18.3</span></a> to show how the different data frames in the <code>nycflights23</code> package are linked by various key variables:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-reldiagram" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-reldiagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/r4ds/relational-nycflights.png" class="img-fluid figure-img" style="width:65.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-reldiagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18.3: Data relationships in nycflights from <em>R for Data Science</em>.
</figcaption>
</figure>
</div>
</div>
</div>
<section id="matching-key-variable-names" class="level4" data-number="18.2.5.1">
<h4 data-number="18.2.5.1" class="anchored" data-anchor-id="matching-key-variable-names"><span class="header-section-number">18.2.5.1</span> Matching key variable names</h4>
<p>In both the <code>flights</code> and <code>airlines</code> data frames, the key variable we want to join/merge/match the rows by has the same name: <code>carrier</code>. Let’s use the <code>inner_join()</code> function to join the two data frames, where the rows will be matched by the variable <code>carrier</code>, and then compare the resulting data frames:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>flights_joined <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(airlines, <span class="at">by =</span> <span class="st">"carrier"</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(flights)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(flights_joined)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Observe that the <code>flights</code> and <code>flights_joined</code> data frames are identical except that <code>flights_joined</code> has an additional variable <code>name</code>. The values of <code>name</code> correspond to the airline companies’ names as indicated in the <code>airlines</code> data frame.</p>
<p>A visual representation of the <code>inner_join()</code> is shown in Figure <a href="#fig-ijdiagram" class="quarto-xref">Figure&nbsp;<span>18.4</span></a>. There are other types of joins available (such as <code>left_join()</code>, <code>right_join()</code>, <code>outer_join()</code>, and <code>anti_join()</code>), but the <code>inner_join()</code> will solve nearly all of the problems you’ll encounter in this book.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ijdiagram" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ijdiagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/r4ds/join-inner.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ijdiagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18.4: Diagram of inner join from <em>R for Data Science</em>.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="sec-diff-key" class="level4" data-number="18.2.5.2">
<h4 data-number="18.2.5.2" class="anchored" data-anchor-id="sec-diff-key"><span class="header-section-number">18.2.5.2</span> Different key variable names</h4>
<p>Say instead you are interested in the destinations of all domestic flights departing NYC in 2023, and you ask yourself questions like: “What cities are these airports in?”, or “Is <code>"ORD"</code> Orlando?”, or “Where is <code>"FLL"</code>?”.</p>
<p>The <code>airports</code> data frame contains the airport codes for each airport:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(airports)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>However, if you look at both the <code>airports</code> and <code>flights</code> data frames, you’ll find that the airport codes are in variables that have different names. In <code>airports</code>, the airport code is in <code>faa</code>, whereas in <code>flights</code> the airport codes are in <code>origin</code> and <code>dest</code>. This fact is further highlighted in the visual representation of the relationships between these data frames in Figure <a href="#fig-reldiagram" class="quarto-xref">Figure&nbsp;<span>18.3</span></a>.</p>
<p>In order to join these two data frames by airport code, our <code>inner_join()</code> operation will use the <code>by = c("dest" = "faa")</code> argument with modified code syntax allowing us to join two data frames where the key variable has a different name:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>flights_with_airport_names <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(airports, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"dest"</span> <span class="ot">=</span> <span class="st">"faa"</span>))</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(flights_with_airport_names)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Let’s construct the chain of pipe operators <code>|&gt;</code> that computes the number of flights from NYC to each destination, but also includes information about each destination airport:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>named_dests <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(dest) <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">num_flights =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(num_flights)) <span class="sc">|&gt;</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(airports, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"dest"</span> <span class="ot">=</span> <span class="st">"faa"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">airport_name =</span> name)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>named_dests</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 118 × 9
   dest  num_flights airport_name             lat    lon   alt    tz dst   tzone
   &lt;chr&gt;       &lt;int&gt; &lt;chr&gt;                  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;
 1 BOS         19036 General Edward Lawren…  42.4  -71.0    20    -5 A     Amer…
 2 ORD         18200 Chicago O'Hare Intern…  42.0  -87.9   672    -6 A     Amer…
 3 MCO         17756 Orlando International…  28.4  -81.3    96    -5 A     Amer…
 4 ATL         17570 Hartsfield Jackson At…  33.6  -84.4  1026    -5 A     Amer…
 5 MIA         16076 Miami International A…  25.8  -80.3     8    -5 A     Amer…
 6 LAX         15968 Los Angeles Internati…  33.9 -118.    125    -8 A     Amer…
 7 FLL         14239 Fort Lauderdale Holly…  26.1  -80.2     9    -5 A     Amer…
 8 CLT         12866 Charlotte Douglas Int…  35.2  -80.9   748    -5 A     Amer…
 9 DFW         11675 Dallas Fort Worth Int…  32.9  -97.0   607    -6 A     Amer…
10 SFO         11651 San Francisco Interna…  37.6 -122.     13    -8 A     Amer…
# ℹ 108 more rows</code></pre>
</div>
</div>
<p>In case you didn’t know, <code>"ORD"</code> is the airport code of Chicago O’Hare airport and <code>"FLL"</code> is the main airport in Fort Lauderdale, Florida, which can be seen in the <code>airport_name</code> variable.</p>
</section>
<section id="multiple-key-variables" class="level4" data-number="18.2.5.3">
<h4 data-number="18.2.5.3" class="anchored" data-anchor-id="multiple-key-variables"><span class="header-section-number">18.2.5.3</span> Multiple key variables</h4>
<p>Say instead we want to join two data frames by <em>multiple key variables</em>. For example, in Figure <a href="#fig-reldiagram" class="quarto-xref">Figure&nbsp;<span>18.3</span></a>, we see that in order to join the <code>flights</code> and <code>weather</code> data frames, we need more than one key variable: <code>year</code>, <code>month</code>, <code>day</code>, <code>hour</code>, and <code>origin</code>. This is because the combination of these 5 variables act to uniquely identify each observational unit in the <code>weather</code> data frame: hourly weather recordings at each of the 3 NYC airports.</p>
<p>We achieve this by specifying a <em>vector</em> of key variables to join by using the <code>c()</code> function. Recall from Subsection <a href="05_module_2_application.html#sec-programming-concepts" class="quarto-xref"><span>Section 6.2.1</span></a> that <code>c()</code> is short for “combine” or “concatenate.” </p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>flights_weather_joined <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(weather, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"year"</span>, <span class="st">"month"</span>, <span class="st">"day"</span>, <span class="st">"hour"</span>, <span class="st">"origin"</span>))</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(flights_weather_joined)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="sec-normal-forms" class="level3" data-number="18.2.6">
<h3 data-number="18.2.6" class="anchored" data-anchor-id="sec-normal-forms"><span class="header-section-number">18.2.6</span> Normal forms</h3>
<p>The data frames included in the <code>nycflights23</code> package are in a form that minimizes redundancy of data. For example, the <code>flights</code> data frame only saves the <code>carrier</code> code of the airline company; it does not include the actual name of the airline. For example, you’ll see that the first row of <code>flights</code> has <code>carrier</code> equal to <code>UA</code>, but it does not include the airline name “United Air Lines Inc.”</p>
<p>The names of the airline companies are included in the <code>name</code> variable of the <code>airlines</code> data frame. In order to have the airline company name included in <code>flights</code>, we could join these two data frames as follows:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>joined_flights <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(airlines, <span class="at">by =</span> <span class="st">"carrier"</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(joined_flights)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We can perform this join because each of the data frames has <em>keys</em> in common to relate one to another: the <code>carrier</code> variable in both the <code>flights</code> and <code>airlines</code> data frames. The <em>key</em> variable(s) that we base our joins on are often <em>identification variables</em> as we mentioned previously.</p>
<p>This is an important property of what’s known as <em>normal forms</em> of data. The process of decomposing data frames into less redundant tables without losing information is called <em>normalization</em>. More information is available on <a href="https://en.wikipedia.org/wiki/Database_normalization">Wikipedia</a>.</p>
<p>Both <code>dplyr</code> and <a href="https://en.wikipedia.org/wiki/SQL">SQL</a> we mentioned in the introduction of this chapter use such <em>normal forms</em>. Given that they share such commonalities, once you learn either of these two tools, you can learn the other very easily.</p>
</section>
<section id="sec-other-verbs" class="level3" data-number="18.2.7">
<h3 data-number="18.2.7" class="anchored" data-anchor-id="sec-other-verbs"><span class="header-section-number">18.2.7</span> Other verbs</h3>
<p>Here are some other useful data-wrangling verbs:</p>
<ul>
<li><code>select()</code> only a subset of variables/columns.</li>
<li><code>relocate()</code> variables/columns to a new position.</li>
<li><code>rename()</code> variables/columns to have new names.</li>
<li>Return only the <code>top_n()</code> values of a variable.</li>
</ul>
<section id="sec-select" class="level4" data-number="18.2.7.1">
<h4 data-number="18.2.7.1" class="anchored" data-anchor-id="sec-select"><span class="header-section-number">18.2.7.1</span> <code>select</code> variables</h4>
<div class="cell">
<div class="cell-output-display">
<div id="fig-selectfig" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-selectfig-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/cheatsheets/select.png" class="img-fluid figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-selectfig-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18.5: Diagram of select() columns.
</figcaption>
</figure>
</div>
</div>
</div>
<p>We’ve seen that the <code>flights</code> data frame in the <code>nycflights23</code> package contains 19 different variables. You can identify the names of these 19 variables by running the <code>glimpse()</code> function from the <code>dplyr</code> package:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(flights)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>However, say you only need two of these 19 variables, say <code>carrier</code> and <code>flight</code>. You can <code>select()</code> these two variables:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>flights <span class="sc">|&gt;</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(carrier, flight)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This function makes it easier to explore large datasets since it allows us to limit the scope to only those variables we care most about. For example, if we <code>select()</code> only a smaller number of variables as is shown in Figure <a href="#fig-selectfig" class="quarto-xref">Figure&nbsp;<span>18.5</span></a>, it will make viewing the dataset in RStudio’s spreadsheet viewer more digestible.</p>
<p>Let’s say instead you want to drop, or de-select, certain variables. For example, consider the variable <code>year</code> in the <code>flights</code> data frame. This variable isn’t quite a “variable” because it is always <code>2023</code> and hence doesn’t change. Say you want to remove this variable from the data frame. We can deselect <code>year</code> by using the <code>-</code> sign:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>flights_no_year <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="sc">-</span>year)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Another way of selecting columns/variables is by specifying a range of columns:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>flight_arr_times <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> <span class="fu">select</span>(month<span class="sc">:</span>day, arr_time<span class="sc">:</span>sched_arr_time)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>flight_arr_times</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This will <code>select()</code> all columns between <code>month</code> and <code>day</code>, as well as between <code>arr_time</code> and <code>sched_arr_time</code>, and drop the rest.</p>
<p>The helper functions <code>starts_with()</code>, <code>ends_with()</code>, and <code>contains()</code> can be used to select variables/columns that match those conditions. As examples,</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>flights <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="fu">starts_with</span>(<span class="st">"a"</span>))</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>flights <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="fu">ends_with</span>(<span class="st">"delay"</span>))</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>flights <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">"time"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Lastly, the <code>select()</code> function can also be used to reorder columns when used with the <code>everything()</code> helper function. For example, suppose we want the <code>hour</code>, <code>minute</code>, and <code>time_hour</code> variables to appear immediately after the <code>year</code>, <code>month</code>, and <code>day</code> variables, while not discarding the rest of the variables. In the following code, <code>everything()</code> will pick up all remaining variables:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>flights_reorder <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(year, month, day, hour, minute, time_hour, <span class="fu">everything</span>())</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(flights_reorder)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="sec-relocate" class="level4" data-number="18.2.7.2">
<h4 data-number="18.2.7.2" class="anchored" data-anchor-id="sec-relocate"><span class="header-section-number">18.2.7.2</span> <code>relocate</code> variables</h4>
<p>Another (usually shorter) way to reorder variables is by using the <code>relocate()</code> function. This function allows you to move variables to a new position in the data frame. For example, if we want to move the <code>hour</code>, <code>minute</code>, and <code>time_hour</code> variables to appear immediately after the <code>year</code>, <code>month</code>, and <code>day</code> variables, we can use the following code:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>flights_relocate <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(hour, minute, time_hour, <span class="at">.after =</span> day)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(flights_relocate)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="sec-rename" class="level4" data-number="18.2.7.3">
<h4 data-number="18.2.7.3" class="anchored" data-anchor-id="sec-rename"><span class="header-section-number">18.2.7.3</span> <code>rename</code> variables</h4>
<p>One more useful function is <code>rename()</code>, which as you may have guessed changes the name of variables. Suppose we want to only focus on <code>dep_time</code> and <code>arr_time</code> and change <code>dep_time</code> and <code>arr_time</code> to be <code>departure_time</code> and <code>arrival_time</code> instead in the <code>flights_time_new</code> data frame:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>flights_time_new <span class="ot">&lt;-</span> flights <span class="sc">|&gt;</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(dep_time, arr_time) <span class="sc">|&gt;</span> </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">departure_time =</span> dep_time, <span class="at">arrival_time =</span> arr_time)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(flights_time_new)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Note that in this case we used a single <code>=</code> sign within the <code>rename()</code>. For example, <code>departure_time = dep_time</code> renames the <code>dep_time</code> variable to have the new name <code>departure_time</code>. This is because we are not testing for equality like we would using <code>==</code>. Instead we want to assign a new variable <code>departure_time</code> to have the same values as <code>dep_time</code> and then delete the variable <code>dep_time</code>. Note that new <code>dplyr</code> users often forget that the new variable name comes before the equal sign.</p>
</section>
</section>
<section id="top_n-values-of-a-variable" class="level3" data-number="18.2.8">
<h3 data-number="18.2.8" class="anchored" data-anchor-id="top_n-values-of-a-variable"><span class="header-section-number">18.2.8</span> <code>top_n</code> values of a variable</h3>
<p>We can also return the top <code>n</code> values of a variable using the <code>top_n()</code> function. For example, we can return a data frame of the top 10 destination airports using the example from Subsection <a href="#sec-diff-key" class="quarto-xref"><span>Section 18.2.5.2</span></a>. Observe that we set the number of values to return to <code>n = 10</code> and <code>wt = num_flights</code> to indicate that we want the rows corresponding to the top 10 values of <code>num_flights</code>. See the help file for <code>top_n()</code> by running <code>?top_n</code> for more information.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>named_dests <span class="sc">|&gt;</span> <span class="fu">top_n</span>(<span class="at">n =</span> <span class="dv">10</span>, <span class="at">wt =</span> num_flights)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Let’s further <code>arrange()</code> these results in descending order of <code>num_flights</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>named_dests <span class="sc">|&gt;</span> </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">top_n</span>(<span class="at">n =</span> <span class="dv">10</span>, <span class="at">wt =</span> num_flights) <span class="sc">|&gt;</span> </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(num_flights))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="tidying-data" class="level2" data-number="18.3">
<h2 data-number="18.3" class="anchored" data-anchor-id="tidying-data"><span class="header-section-number">18.3</span> Tidying Data</h2>
<p>In Subsection <a href="05_module_2_application.html#sec-programming-concepts" class="quarto-xref"><span>Section 6.2.1</span></a>, I introduced the concept of a data frame in R: a rectangular spreadsheet-like representation of data where the rows correspond to observations and the columns correspond to variables describing each observation. In Section <a href="05_module_2_application.html#sec-nycflights" class="quarto-xref"><span>Section 6.4</span></a>, we started exploring our first data frame: the <code>flights</code> data frame included in the <code>nycflights23</code> package.</p>
<p>In the first section of this walkthrough, we learned how to take existing data frames and transform/modify them to suit our ends. In this second section, we extend some of these ideas by discussing a type of data formatting called “tidy” data. You will see that having data stored in “tidy” format is about more than just what the everyday definition of the term “tidy” might suggest: having your data “neatly organized.” Instead, we define the term “tidy” as it’s used by data scientists who use R, outlining a set of rules by which data is saved.</p>
<p>Knowing about tidy data was not necessary earlier because all the data we used were already in “tidy” format. In this walkthrough, we’ll now see that this format is essential to using the tools we’ve covered. Furthermore, it will also be useful for future walkthroughs as we cover future ideas.</p>
<section id="sec-tidy-packages" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="sec-tidy-packages">Needed packages</h3>
<p>Let’s load all the packages needed for this walkthrough (this assumes you’ve already installed them). If needed, read Section <a href="05_module_2_application.html#sec-packages" class="quarto-xref"><span>Section 6.3</span></a> for information on how to install and load R packages.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nycflights23)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fivethirtyeight)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Note that when you load the <code>fivethirtyeight</code> package, you’ll receive the following message:</p>
<blockquote class="blockquote">
<p>Some larger datasets need to be installed separately, like senators and house_district_forecast. To install these, we recommend you install the fivethirtyeightdata package by running: install.packages(‘fivethirtyeightdata’, repos = ‘https://fivethirtyeightdata.github.io/drat/’, type = ‘source’)</p>
</blockquote>
<p>This message can be ignored for the purposes of this book, but if you’d like to explore these larger datasets, you can install the <code>fivethirtyeightdata</code> package as suggested.</p>
</section>
<section id="sec-csv" class="level3" data-number="18.3.1">
<h3 data-number="18.3.1" class="anchored" data-anchor-id="sec-csv"><span class="header-section-number">18.3.1</span> Importing data</h3>
<p>Up to this point, most of our activities have used data stored inside of an R package, though we <em>have</em> practiced importing data from an outside source in Section <a href="11_module_4_application.html#sec-loading-dataset" class="quarto-xref"><span>Section 12.4</span></a>. It’s time to put that practice to use!</p>
<p>To practice tidying data, we need to load a <em>Comma Separated Values</em> <code>.csv</code> file, the same format that I encouraged you to find for your personal dataset. You can think of a <code>.csv</code> file as a bare-bones spreadsheet where:</p>
<ul>
<li>Each line in the file corresponds to one row of data/one observation.</li>
<li>Values for each line are separated with commas. In other words, the values of different variables are separated by commas in each row.</li>
<li>The first line is often, but not always, a <em>header</em> row indicating the names of the columns/variables.</li>
</ul>
<p>The <code>.csv</code> file we’re interested in here is <code>dem_score.csv</code>—it is found in the <code>activity_data</code> subfolder of your class project folder and contains ratings of the level of democracy in different countries spanning 1952 to 1992. Let’s use the <code>read_csv()</code> function from the <code>readr</code> package (with some help from the <code>@here</code> package) to read it from your computer, import it into R, and save it in a data frame called <code>dem_score</code>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>dem_score <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"activity_data"</span>,<span class="st">"dem_score.csv"</span>))</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>dem_score</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 96 × 10
   country    `1952` `1957` `1962` `1967` `1972` `1977` `1982` `1987` `1992`
   &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 Albania        -9     -9     -9     -9     -9     -9     -9     -9      5
 2 Argentina      -9     -1     -1     -9     -9     -9     -8      8      7
 3 Armenia        -9     -7     -7     -7     -7     -7     -7     -7      7
 4 Australia      10     10     10     10     10     10     10     10     10
 5 Austria        10     10     10     10     10     10     10     10     10
 6 Azerbaijan     -9     -7     -7     -7     -7     -7     -7     -7      1
 7 Belarus        -9     -7     -7     -7     -7     -7     -7     -7      7
 8 Belgium        10     10     10     10     10     10     10     10     10
 9 Bhutan        -10    -10    -10    -10    -10    -10    -10    -10    -10
10 Bolivia        -4     -3     -3     -4     -7     -7      8      9      9
# ℹ 86 more rows</code></pre>
</div>
</div>
<p>In this <code>dem_score</code> data frame, the minimum value of <code>-10</code> corresponds to a highly autocratic nation, whereas a value of <code>10</code> corresponds to a highly democratic nation. Note also that backticks surround the different variable names. Variable names in R by default are not allowed to start with a number nor include spaces, but we can get around this fact by surrounding the column name with backticks. We’ll revisit the <code>dem_score</code> data frame in a case study in the upcoming Section <a href="#sec-case-study-tidy" class="quarto-xref"><span>Section 18.3.5</span></a>.</p>
<p>Note that the <code>read_csv()</code> function included in the <code>readr</code> package is different than the <code>read.csv()</code> function that comes installed with R. While the difference in the names might seem trivial (an <code>_</code> instead of a <code>.</code>), the <code>read_csv()</code> function is, in my opinion, easier to use since it can more easily read data off the web and generally imports data at a much faster speed. Furthermore, the <code>read_csv()</code> function included in the <code>readr</code> saves data frames as <code>tibbles</code> by default.</p>
</section>
<section id="sec-tidy-data-ex" class="level3" data-number="18.3.2">
<h3 data-number="18.3.2" class="anchored" data-anchor-id="sec-tidy-data-ex"><span class="header-section-number">18.3.2</span> “Tidy” data</h3>
<p>With our data imported, let’s learn about the concept of “tidy” data format with a motivating example from the <code>fivethirtyeight</code> package. The <code>fivethirtyeight</code> package provides access to the datasets used in many articles published by the now-slightly-defunct data journalism website, <a href="https://fivethirtyeight.com/">FiveThirtyEight.com</a>. For a complete list of all 129 datasets included in the <code>fivethirtyeight</code> package, check out the package webpage by going to: <a href="https://fivethirtyeight-r.netlify.app/articles/fivethirtyeight.html" class="uri">https://fivethirtyeight-r.netlify.app/articles/fivethirtyeight.html</a>.</p>
<p>Let’s focus our attention on the <code>drinks</code> data frame and look at its first 5 rows:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  country     beer_servings spirit_servings wine_servings total_litres_of_pure…¹
  &lt;chr&gt;               &lt;int&gt;           &lt;int&gt;         &lt;int&gt;                  &lt;dbl&gt;
1 Afghanistan             0               0             0                    0  
2 Albania                89             132            54                    4.9
3 Algeria                25               0            14                    0.7
4 Andorra               245             138           312                   12.4
5 Angola                217              57            45                    5.9
# ℹ abbreviated name: ¹​total_litres_of_pure_alcohol</code></pre>
</div>
</div>
<p>After reading the help file by running <code>?drinks</code>, you’ll see that <code>drinks</code> is a data frame containing results from a survey of the average number of servings of beer, spirits, and wine consumed in 193 countries. This data was originally reported on FiveThirtyEight.com in Mona Chalabi’s article: <a href="https://fivethirtyeight.com/features/dear-mona-followup-where-do-people-drink-the-most-beer-wine-and-spirits/">“Dear Mona Followup: Where Do People Drink The Most Beer, Wine And Spirits?”</a>. It’s important to note that Chalabi is no longer with FiveThirtyEight and <a href="https://x.com/MonaChalabi/status/1270715883531300866">has been sharply critical</a> of the organization since her leaving.</p>
<p>Let’s apply some of the data wrangling verbs we learned in Section <a href="#sec-wrangling" class="quarto-xref"><span>Chapter 18</span></a> on the <code>drinks</code> data frame:</p>
<ol type="1">
<li><code>filter()</code> the <code>drinks</code> data frame to only consider 4 countries: the United States, China, Italy, and Saudi Arabia, <em>then</em></li>
<li><code>select()</code> all columns except <code>total_litres_of_pure_alcohol</code> by using the <code>-</code> sign, <em>then</em></li>
<li><code>rename()</code> the variables <code>beer_servings</code>, <code>spirit_servings</code>, and <code>wine_servings</code> to <code>beer</code>, <code>spirit</code>, and <code>wine</code>, respectively.</li>
</ol>
<p>and save the resulting data frame in <code>drinks_smaller</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>drinks_smaller <span class="ot">&lt;-</span> drinks <span class="sc">|&gt;</span> </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(country <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"USA"</span>, <span class="st">"China"</span>, <span class="st">"Italy"</span>, <span class="st">"Saudi Arabia"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>total_litres_of_pure_alcohol) <span class="sc">|&gt;</span> </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">beer =</span> beer_servings, <span class="at">spirit =</span> spirit_servings, <span class="at">wine =</span> wine_servings)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>drinks_smaller</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  country       beer spirit  wine
  &lt;chr&gt;        &lt;int&gt;  &lt;int&gt; &lt;int&gt;
1 China           79    192     8
2 Italy           85     42   237
3 Saudi Arabia     0      5     0
4 USA            249    158    84</code></pre>
</div>
</div>
<p>Let’s compare this way of organizing the data with an alternative:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>drinks_smaller_tidy <span class="ot">&lt;-</span> drinks_smaller <span class="sc">|&gt;</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>(type, servings, <span class="sc">-</span>country)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>drinks_smaller_tidy</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 3
   country      type   servings
   &lt;chr&gt;        &lt;chr&gt;     &lt;int&gt;
 1 China        beer         79
 2 Italy        beer         85
 3 Saudi Arabia beer          0
 4 USA          beer        249
 5 China        spirit      192
 6 Italy        spirit       42
 7 Saudi Arabia spirit        5
 8 USA          spirit      158
 9 China        wine          8
10 Italy        wine        237
11 Saudi Arabia wine          0
12 USA          wine         84</code></pre>
</div>
</div>
<p>Observe that while <code>drinks_smaller</code> and <code>drinks_smaller_tidy</code> are both rectangular in shape and contain the same 12 numerical values (3 alcohol types by 4 countries), they are formatted differently. <code>drinks_smaller</code> is formatted in what’s known as <a href="https://en.wikipedia.org/wiki/Wide_and_narrow_data">“wide”</a> format, whereas <code>drinks_smaller_tidy</code> is formatted in what’s known as <a href="https://en.wikipedia.org/wiki/Wide_and_narrow_data#Narrow">“long/narrow”</a> format.</p>
<p>In the context of doing data science in R, long/narrow format is also known as “tidy” format. In order to use the packages that we prefer in this class, your input data frames <em>must</em> be in “tidy” format. Thus, all non-“tidy” data must be converted to “tidy” format first. Before we convert non-“tidy” data frames like <code>drinks_smaller</code> to “tidy” data frames like <code>drinks_smaller_tidy</code>, let’s define “tidy” data.</p>
</section>
<section id="sec-tidy-definition" class="level3" data-number="18.3.3">
<h3 data-number="18.3.3" class="anchored" data-anchor-id="sec-tidy-definition"><span class="header-section-number">18.3.3</span> Definition of “tidy” data</h3>
<p>You have surely heard the word “tidy” in your life:</p>
<ul>
<li>“Tidy up your room!”</li>
<li>“Write your homework in a tidy way so it is easier to provide feedback.”</li>
<li>Marie Kondo’s best-selling book, <a href="https://www.powells.com/book/-9781607747307"><em>The Life-Changing Magic of Tidying Up: The Japanese Art of Decluttering and Organizing</em></a>, and Netflix TV series <a href="https://www.netflix.com/title/80209379"><em>Tidying Up with Marie Kondo</em></a>.</li>
</ul>
<p>What does it mean for your data to be “tidy”? While “tidy” has a clear English meaning of “organized,” the word “tidy” in data science using R means that your data follows a standardized format. We will follow Hadley Wickham’s (2014) definition of <em>“tidy” data</em> shown also in Figure <a href="#fig-tidyfig" class="quarto-xref">Figure&nbsp;<span>18.6</span></a>:</p>
<blockquote class="blockquote">
<p>A <em>dataset</em> is a collection of values, usually either numbers (if quantitative) or strings AKA text data (if qualitative/categorical). Values are organised in two ways. Every value belongs to a variable and an observation. A variable contains all values that measure the same underlying attribute (like height, temperature, duration) across units. An observation contains all values measured on the same unit (like a person, or a day, or a city) across attributes.</p>
<p>“Tidy” data is a standard way of mapping the meaning of a dataset to its structure. A dataset is messy or tidy depending on how rows, columns and tables are matched up with observations, variables and types. In <em>tidy data</em>:</p>
<ol type="1">
<li>Each variable forms a column.</li>
<li>Each observation forms a row.</li>
<li>Each type of observational unit forms a table.</li>
</ol>
</blockquote>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-tidyfig" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tidyfig-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/r4ds/tidy-1.png" class="quarto-figure quarto-figure-center figure-img" style="width:80.0%;height:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tidyfig-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18.6: Tidy data graphic from <em>R for Data Science</em>.
</figcaption>
</figure>
</div>
</div>
</div>
<p>For example, say you have the following table of stock prices in Table <a href="#tbl-non-tidy-stocks" class="quarto-xref">Table&nbsp;<span>18.2</span></a>:</p>
<div class="cell" data-layout-align="center">
<div id="tbl-non-tidy-stocks" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-non-tidy-stocks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;18.2: Stock prices (non-tidy format)
</figcaption>
<div aria-describedby="tbl-non-tidy-stocks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Date</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Boeing stock price</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Amazon stock price</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Google stock price</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2009-01-01</td>
<td style="text-align: left;">$173.55</td>
<td style="text-align: left;">$174.90</td>
<td style="text-align: left;">$174.34</td>
</tr>
<tr class="even">
<td style="text-align: left;">2009-01-02</td>
<td style="text-align: left;">$172.61</td>
<td style="text-align: left;">$171.42</td>
<td style="text-align: left;">$170.04</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Although the data are neatly organized in a rectangular spreadsheet-type format, they do not follow the definition of data in “tidy” format. While there are three variables corresponding to three unique pieces of information (date, stock name, and stock price), there are not three columns. In “tidy” data format, each variable should be its own column, as shown in Table <a href="#tbl-tidy-stocks" class="quarto-xref">Table&nbsp;<span>18.3</span></a>. Notice that both tables present the same information, but in different formats.</p>
<p>Although the data is in a rectangular spreadsheet format, it is not “tidy.” There are three variables (date, stock name, and stock price), but not three separate columns. In tidy data, each variable should have its own column, as shown in Table <a href="#tbl-tidy-stocks" class="quarto-xref">Table&nbsp;<span>18.3</span></a>. Both tables present the same information, but in different formats.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-tidy-stocks" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tidy-stocks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;18.3: Stock prices (tidy format)
</figcaption>
<div aria-describedby="tbl-tidy-stocks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Date</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Stock Name</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Stock Price</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2009-01-01</td>
<td style="text-align: left;">Boeing</td>
<td style="text-align: left;">$173.55</td>
</tr>
<tr class="even">
<td style="text-align: left;">2009-01-01</td>
<td style="text-align: left;">Amazon</td>
<td style="text-align: left;">$174.90</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2009-01-01</td>
<td style="text-align: left;">Google</td>
<td style="text-align: left;">$174.34</td>
</tr>
<tr class="even">
<td style="text-align: left;">2009-01-02</td>
<td style="text-align: left;">Boeing</td>
<td style="text-align: left;">$172.61</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2009-01-02</td>
<td style="text-align: left;">Amazon</td>
<td style="text-align: left;">$171.42</td>
</tr>
<tr class="even">
<td style="text-align: left;">2009-01-02</td>
<td style="text-align: left;">Google</td>
<td style="text-align: left;">$170.04</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>On the other hand, consider the data in Table <a href="#tbl-tidy-stocks-2" class="quarto-xref">Table&nbsp;<span>18.4</span></a>.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-tidy-stocks-2" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-tidy-stocks-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;18.4: Example of tidy data
</figcaption>
<div aria-describedby="tbl-tidy-stocks-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Date</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Boeing Price</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Weather</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2009-01-01</td>
<td style="text-align: left;">$173.55</td>
<td style="text-align: left;">Sunny</td>
</tr>
<tr class="even">
<td style="text-align: left;">2009-01-02</td>
<td style="text-align: left;">$172.61</td>
<td style="text-align: left;">Overcast</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>In this case, even though the variable “Boeing Price” occurs just like in our non-“tidy” data in Table <a href="#tbl-non-tidy-stocks" class="quarto-xref">Table&nbsp;<span>18.2</span></a>, the data <em>is</em> “tidy” since there are three variables for each of three unique pieces of information: Date, Boeing price, and the Weather that day.</p>
</section>
<section id="converting-to-tidy-data" class="level3" data-number="18.3.4">
<h3 data-number="18.3.4" class="anchored" data-anchor-id="converting-to-tidy-data"><span class="header-section-number">18.3.4</span> Converting to “tidy” data</h3>
<p>In our walkthroughs so far, you’ve only seen data frames that were already in “tidy” format. Furthermore, for the rest of the semester, you’ll mostly only see data frames that are already in “tidy” format as well. However, this is not always the case with all datasets—including, perhaps, the dataset that you’ve chosen to work with for your class projects. If your original data frame is in wide (non-“tidy”) format and you would like to use the packages we learn about, you will first have to convert it to “tidy” format. (If you’re not sure if your data is tidy, reach out and ask me—I can help you figure this out!) To do so, we recommend using the <code>pivot_longer()</code> function in the <code>tidyr</code> package.</p>
<p>Going back to our <code>drinks_smaller</code> data frame from earlier:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>drinks_smaller</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  country       beer spirit  wine
  &lt;chr&gt;        &lt;int&gt;  &lt;int&gt; &lt;int&gt;
1 China           79    192     8
2 Italy           85     42   237
3 Saudi Arabia     0      5     0
4 USA            249    158    84</code></pre>
</div>
</div>
<p>We convert it to “tidy” format by using the <code>pivot_longer()</code> function from the <code>tidyr</code> package as follows:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>drinks_smaller_tidy <span class="ot">&lt;-</span> drinks_smaller <span class="sc">|&gt;</span> </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">names_to =</span> <span class="st">"type"</span>, </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"servings"</span>, </span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">cols =</span> <span class="sc">-</span>country)</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>drinks_smaller_tidy</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 3
   country      type   servings
   &lt;chr&gt;        &lt;chr&gt;     &lt;int&gt;
 1 China        beer         79
 2 China        spirit      192
 3 China        wine          8
 4 Italy        beer         85
 5 Italy        spirit       42
 6 Italy        wine        237
 7 Saudi Arabia beer          0
 8 Saudi Arabia spirit        5
 9 Saudi Arabia wine          0
10 USA          beer        249
11 USA          spirit      158
12 USA          wine         84</code></pre>
</div>
</div>
<p>We set the arguments to <code>pivot_longer()</code> as follows:</p>
<ol type="1">
<li><code>names_to</code> here corresponds to the name of the variable in the new “tidy”/long data frame that will contain the <em>column names</em> of the original data. Observe how we set <code>names_to = "type"</code>. In the resulting <code>drinks_smaller_tidy</code>, the column <code>type</code> contains the three types of alcohol <code>beer</code>, <code>spirit</code>, and <code>wine</code>. Since <code>type</code> is a variable name that doesn’t appear in <code>drinks_smaller</code>, we use quotation marks around it. You’ll receive an error if you just use <code>names_to = type</code> here.</li>
<li><code>values_to</code> here is the name of the variable in the new “tidy” data frame that will contain the <em>values</em> of the original data. Observe how we set <code>values_to = "servings"</code> since each of the numeric values in each of the <code>beer</code>, <code>wine</code>, and <code>spirit</code> columns of the <code>drinks_smaller</code> data corresponds to a value of <code>servings</code>. In the resulting <code>drinks_smaller_tidy</code>, the column <code>servings</code> contains the 4 <span class="math inline">\(\times\)</span> 3 = 12 numerical values. Note again that <code>servings</code> doesn’t appear as a variable in <code>drinks_smaller</code> so it again needs quotation marks around it for the <code>values_to</code> argument.</li>
<li>The third argument <code>cols</code> is the columns in the <code>drinks_smaller</code> data frame you either want to or don’t want to “tidy.” Observe how we set this to <code>-country</code> indicating that we don’t want to “tidy” the <code>country</code> variable in <code>drinks_smaller</code> and rather only <code>beer</code>, <code>spirit</code>, and <code>wine</code>. Since <code>country</code> is a column that appears in <code>drinks_smaller</code> we don’t put quotation marks around it.</li>
</ol>
<p>The third argument here of <code>cols</code> is a little nuanced, so let’s consider code that’s written slightly differently but that produces the same output:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>drinks_smaller <span class="sc">|&gt;</span> </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">names_to =</span> <span class="st">"type"</span>, </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"servings"</span>, </span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">cols =</span> <span class="fu">c</span>(beer, spirit, wine))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Note that the third argument now specifies which columns we want to “tidy” with <code>c(beer, spirit, wine)</code>, instead of the columns we don’t want to “tidy” using <code>-country</code>. We use the <code>c()</code> function to create a vector of the columns in <code>drinks_smaller</code> that we’d like to “tidy.” Note that since these three columns appear one after another in the <code>drinks_smaller</code> data frame, we could also do the following for the <code>cols</code> argument:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>drinks_smaller <span class="sc">|&gt;</span> </span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">names_to =</span> <span class="st">"type"</span>, </span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"servings"</span>, </span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">cols =</span> beer<span class="sc">:</span>wine)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Converting “wide” format data to “tidy” format often confuses new R users. The only way to learn to get comfortable with the <code>pivot_longer()</code> function is with practice, practice, and more practice using different datasets. For example, run <code>?pivot_longer</code> and look at the examples in the bottom of the help file. We’ll show another example of using <code>pivot_longer()</code> to convert a “wide” formatted data frame to “tidy” format in Section <a href="#sec-case-study-tidy" class="quarto-xref"><span>Section 18.3.5</span></a>.</p>
<section id="nycflights23-package" class="level4" data-number="18.3.4.1">
<h4 data-number="18.3.4.1" class="anchored" data-anchor-id="nycflights23-package"><span class="header-section-number">18.3.4.1</span> <code>nycflights23</code> package</h4>
<p>Recall the <code>nycflights23</code> package we introduced in Section <a href="05_module_2_application.html#sec-nycflights" class="quarto-xref"><span>Section 6.4</span></a> with data about all domestic flights departing from New York City in 2023. Let’s revisit the <code>flights</code> data frame by running <code>View(flights)</code>. We saw that <code>flights</code> has a rectangular shape, with each of its 435,352 rows corresponding to a flight and each of its 22 columns corresponding to different characteristics/measurements of each flight. This satisfied the first two criteria of the definition of “tidy” data from Subsection <a href="#sec-tidy-definition" class="quarto-xref"><span>Section 18.3.3</span></a>: that “Each variable forms a column” and “Each observation forms a row.” But what about the third property of “tidy” data that “Each type of observational unit forms a table”?</p>
<p>Recall that we saw in Subsection <a href="05_module_2_application.html#sec-exploredataframes" class="quarto-xref"><span>Section 6.4.3</span></a> that the observational unit for the <code>flights</code> data frame is an individual flight. In other words, the rows of the <code>flights</code> data frame refer to characteristics/measurements of individual flights. Also included in the <code>nycflights23</code> package are other data frames with their rows representing different observational units <span class="citation" data-cites="R-nycflights23">[@R-nycflights23]</span>:</p>
<ul>
<li><code>airlines</code>: translation between two letter IATA carrier codes and airline company names (14 in total). The observational unit is an airline company.</li>
<li><code>planes</code>: aircraft information about each of 4,840 planes used, i.e., the observational unit is an aircraft.</li>
<li><code>weather</code>: hourly meteorological data (about 8,736 observations) for each of the three NYC airports, i.e., the observational unit is an hourly measurement of weather at one of the three airports.</li>
<li><code>airports</code>: airport names and locations. The observational unit is an airport.</li>
</ul>
<p>The organization of the information into these five data frames follows the third “tidy” data property: observations corresponding to the same observational unit should be saved in the same table, i.e., data frame. You could think of this property as the old English expression: “birds of a feather flock together.”</p>
</section>
</section>
<section id="sec-case-study-tidy" class="level3" data-number="18.3.5">
<h3 data-number="18.3.5" class="anchored" data-anchor-id="sec-case-study-tidy"><span class="header-section-number">18.3.5</span> Case study: Democracy in Guatemala</h3>
<p>In this section, we’ll show you another example of how to convert a data frame that isn’t in “tidy” format (“wide” format) to a data frame that is in “tidy” format (“long/narrow” format). We’ll do this using the <code>pivot_longer()</code> function from the <code>tidyr</code> package again.</p>
<p>Let’s use the <code>dem_score</code> data frame we imported in Section <a href="#sec-csv" class="quarto-xref"><span>Section 18.3.1</span></a>, but focus on only data corresponding to Guatemala.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>guat_dem <span class="ot">&lt;-</span> dem_score <span class="sc">|&gt;</span> </span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(country <span class="sc">==</span> <span class="st">"Guatemala"</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>guat_dem</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 10
  country   `1952` `1957` `1962` `1967` `1972` `1977` `1982` `1987` `1992`
  &lt;chr&gt;      &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
1 Guatemala      2     -6     -5      3      1     -3     -7      3      3</code></pre>
</div>
</div>
<p>Now we are stuck in a predicament, much like with our <code>drinks_smaller</code> example in Section <a href="#sec-tidy-data-ex" class="quarto-xref"><span>Section 18.3.2</span></a>. We see that we have a variable named <code>country</code>, but its only value is <code>"Guatemala"</code>. We have other variables denoted by different year values. Unfortunately, the <code>guat_dem</code> data frame is not “tidy.”</p>
<p>We need to take the values of the columns corresponding to years in <code>guat_dem</code> and convert them into a new “names” variable called <code>year</code>. Furthermore, we need to take the democracy score values in the inside of the data frame and turn them into a new “values” variable called <code>democracy_score</code>. Our resulting data frame will have three columns: <code>country</code>, <code>year</code>, and <code>democracy_score</code>. Recall that the <code>pivot_longer()</code> function in the <code>tidyr</code> package does this for us:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>guat_dem_tidy <span class="ot">&lt;-</span> guat_dem <span class="sc">|&gt;</span> </span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">names_to =</span> <span class="st">"year"</span>, </span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"democracy_score"</span>, </span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">cols =</span> <span class="sc">-</span>country,</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_transform =</span> <span class="fu">list</span>(<span class="at">year =</span> as.integer)) </span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>guat_dem_tidy</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 3
  country    year democracy_score
  &lt;chr&gt;     &lt;int&gt;           &lt;dbl&gt;
1 Guatemala  1952               2
2 Guatemala  1957              -6
3 Guatemala  1962              -5
4 Guatemala  1967               3
5 Guatemala  1972               1
6 Guatemala  1977              -3
7 Guatemala  1982              -7
8 Guatemala  1987               3
9 Guatemala  1992               3</code></pre>
</div>
</div>
<p>We set the arguments to <code>pivot_longer()</code> as follows:</p>
<ol type="1">
<li><code>names_to</code> is the name of the variable in the new “tidy” data frame that will contain the <em>column names</em> of the original data. Observe how we set <code>names_to = "year"</code>. In the resulting <code>guat_dem_tidy</code>, the column <code>year</code> contains the years where Guatemala’s democracy scores were measured.</li>
<li><code>values_to</code> is the name of the variable in the new “tidy” data frame that will contain the <em>values</em> of the original data. Observe how we set <code>values_to = "democracy_score"</code>. In the resulting <code>guat_dem_tidy</code> the column <code>democracy_score</code> contains the 1 <span class="math inline">\(\times\)</span> 9 = 9 democracy scores as numeric values.</li>
<li>The third argument is the columns you either want to or don’t want to “tidy.” Observe how we set this to <code>cols = -country</code> indicating that we don’t want to “tidy” the <code>country</code> variable in <code>guat_dem</code> and rather only variables <code>1952</code> through <code>1992</code>.</li>
<li>The last argument of <code>names_transform</code> tells R what type of variable <code>year</code> should be set to. Without specifying that it is an <code>integer</code> as we’ve done here, <code>pivot_longer()</code> will set it to be a character value by default.</li>
</ol>
</section>
</section>
<section id="sec-tidyverse-package" class="level2" data-number="18.4">
<h2 data-number="18.4" class="anchored" data-anchor-id="sec-tidyverse-package"><span class="header-section-number">18.4</span> <code>tidyverse</code> package</h2>
<p>Notice at the beginning of the chapter we loaded the following three packages, which are among the most frequently used R packages for data science:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Recall that <code>dplyr</code> is for data wrangling, <code>readr</code> is for importing spreadsheet data into R, and <code>tidyr</code> is for converting data to “tidy” format. There is a much quicker way to load these packages than by individually loading them: by installing and loading the <code>tidyverse</code> package. The <code>tidyverse</code> package acts as an “umbrella” package whereby installing/loading it will install/load multiple packages at once for you.</p>
<p>After installing the <code>tidyverse</code> package as you would a normal package (as seen in Section <a href="05_module_2_application.html#sec-packages" class="quarto-xref"><span>Section 6.3</span></a>), running:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>would be the same as running:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(purrr)</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forcats)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We’ll cover <code>ggplot2</code> in a future walk through, but the other packages are more than we need in 661. You can check out <em><a href="https://r4ds.had.co.nz/">R for Data Science</a></em> to learn about these packages.</p>
<p>For the remainder of this book, we’ll start every walkthrough by running <code>library(tidyverse)</code>, instead of loading the various component packages individually. The <code>tidyverse</code> “umbrella” package gets its name from the fact that all the functions in all its packages are designed to have common inputs and outputs: data frames are in “tidy” format. This standardization of input and output data frames makes transitions between different functions in the different packages as seamless as possible. For more information, check out the <a href="https://www.tidyverse.org/">tidyverse.org</a> webpage for the package.</p>
</section>
<section id="references" class="level2" data-number="18.5">
<h2 data-number="18.5" class="anchored" data-anchor-id="references"><span class="header-section-number">18.5</span> References</h2>
<p>Grolemund, G., &amp; Wickham, H. (2017). <em>R for Data Science</em> (1st edition). O’Reilly Media. https://r4ds.had.co.nz/.</p>
<p>Wickham, H. (2014). Tidy data. <em>Journal of Statistical Software</em>, <em>59</em>(10). https://www.jstatsoft.org/index.php/jss/article/view/v059i10/v59i10.pdf.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./16_module_6_understanding.html" class="pagination-link" aria-label="M6U: Unicorns, Janitors, and Rock Stars">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">M6U: Unicorns, Janitors, and Rock Stars</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./18_module_6_connection.html" class="pagination-link" aria-label="M6C: Practice Wrangling and Tidying Your Own Data">
        <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">M6C: Practice Wrangling and Tidying Your Own Data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>