<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>27&nbsp; M9A: Basic Regression – Introduction to Data Science</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./27_module_9_connection.html" rel="next">
<link href="./25_module_9_understanding.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./26_module_9_application.html"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">M9A: Basic Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Data Science</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to Data Science</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_module_1_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">M1U: Course Syllabus</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_module_1_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">M1A: Install R and RStudio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_module_1_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">M1C: Introduce Yourself to the Class</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_module_2_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">M2U: The New(?) and Shiny(?) Science of Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_module_2_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">M2A: Getting Started with Data in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_module_2_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">M2C: Set up GitHub</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_module_3_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">M3U: Research Paradigms and Reproducibility</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_module_3_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">M3A: Using Projects and Scripts in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_module_3_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">M3C: Writing in R Markdown</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_module_4_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">M4U: The Value of Open Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_module_4_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">M4A: Find a Dataset Relevant To You</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12_module_4_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">M4C: Show Your Work</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13_module_5_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">M5U: Numbers Don’t Speak for Themselves</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14_module_5_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">M5A: Are Ethics Enough in Data Science?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15_module_5_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">M5C: Reflect on Theoretical and Philosophical Constraints</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16_module_6_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">M6U: Unicorns, Janitors, and Rock Stars</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17_module_6_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">M6A: Wrangling and Tidying Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18_module_6_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">M6C: Practice Wrangling and Tidying Your Own Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19_module_7_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">M7U: Subjectivity in Data Visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20_module_7_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">M7A: Data Visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21_module_7_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">M7C: Practice Visualizing Your Own Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22_module_8_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">M8U: Statistics and Scientific Racism</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23_module_8_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">M8A: Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24_module_8_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">M8C: Calculate Descriptive Statistics for Your Own Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25_module_9_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">M9U: Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./26_module_9_application.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">M9A: Basic Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./27_module_9_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">M9C: Perform a Basic Regression With Your Own Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./28_module_10_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">M10U: Consequences of Failed Predictions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./29_module_10_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">M10A: Multiple Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./30_module_10_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">M10C: Perform a Multiple Regression With Your Own Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./31_module_11_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">M11U: Samples and Populations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./32_module_11_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">M11A: Sampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./33_module_11_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">M11C: Explore Sampling With Your Own Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./34_module_12_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">M12U: Confident About What?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./35_module_12_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">M12A: Confidence Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./36_module_12_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">M12C: Explore Confidence Intervals With Your Own Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./37_module_13_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">M13U: The Dangers of False Positives</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./38_module_13_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">M13: Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./39_module_13_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">M13C: Explore Hypothesis Testing With Your Own Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./40_module_14_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">M14U: Small Stories vs.&nbsp;Big Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./41_module_14_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">M14A: Inferential Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./42_module_14_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">M14C: Perform an Inferential Regression With Your Own Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./43_module_15_understanding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">M15U: Reflect on Your Understanding of Data Science</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./44_module_15_application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">M15A: Reflect on Your Application of Data Science</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./45_module_15_connection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">M15C: Reflect on Your Connection of Data Science</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">27.1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#sec-reg-packages" id="toc-sec-reg-packages" class="nav-link" data-scroll-target="#sec-reg-packages">Needed packages</a></li>
  </ul></li>
  <li><a href="#sec-model1" id="toc-sec-model1" class="nav-link" data-scroll-target="#sec-model1"><span class="header-section-number">27.2</span> One numerical explanatory variable</a>
  <ul class="collapse">
  <li><a href="#sec-model1EDA" id="toc-sec-model1EDA" class="nav-link" data-scroll-target="#sec-model1EDA"><span class="header-section-number">27.2.1</span> Exploratory data analysis</a></li>
  <li><a href="#sec-model1table" id="toc-sec-model1table" class="nav-link" data-scroll-target="#sec-model1table"><span class="header-section-number">27.2.2</span> Simple linear regression</a></li>
  <li><a href="#sec-model1points" id="toc-sec-model1points" class="nav-link" data-scroll-target="#sec-model1points"><span class="header-section-number">27.2.3</span> Observed/fitted values and residuals</a></li>
  </ul></li>
  <li><a href="#sec-model2" id="toc-sec-model2" class="nav-link" data-scroll-target="#sec-model2"><span class="header-section-number">27.3</span> One categorical explanatory variable</a>
  <ul class="collapse">
  <li><a href="#sec-model2EDA" id="toc-sec-model2EDA" class="nav-link" data-scroll-target="#sec-model2EDA"><span class="header-section-number">27.3.1</span> Exploratory data analysis</a></li>
  <li><a href="#sec-model2table" id="toc-sec-model2table" class="nav-link" data-scroll-target="#sec-model2table"><span class="header-section-number">27.3.2</span> Linear regression</a></li>
  <li><a href="#sec-model2points" id="toc-sec-model2points" class="nav-link" data-scroll-target="#sec-model2points"><span class="header-section-number">27.3.3</span> Observed/fitted values and residuals</a></li>
  </ul></li>
  <li><a href="#sec-reg-related-topics" id="toc-sec-reg-related-topics" class="nav-link" data-scroll-target="#sec-reg-related-topics"><span class="header-section-number">27.4</span> Related topics</a>
  <ul class="collapse">
  <li><a href="#sec-correlation-is-not-causation" id="toc-sec-correlation-is-not-causation" class="nav-link" data-scroll-target="#sec-correlation-is-not-causation"><span class="header-section-number">27.4.1</span> Correlation is not necessarily causation</a></li>
  <li><a href="#sec-leastsquares" id="toc-sec-leastsquares" class="nav-link" data-scroll-target="#sec-leastsquares"><span class="header-section-number">27.4.2</span> Best-fitting line</a></li>
  <li><a href="#sec-underthehood" id="toc-sec-underthehood" class="nav-link" data-scroll-target="#sec-underthehood"><span class="header-section-number">27.4.3</span> get_regression_x() functions</a></li>
  </ul></li>
  <li><a href="#sec-reg-conclusion" id="toc-sec-reg-conclusion" class="nav-link" data-scroll-target="#sec-reg-conclusion"><span class="header-section-number">27.5</span> Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">27.6</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">M9A: Basic Regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This content draws on material from <em><a href="https://moderndive.com/v2">Statistical Inference via Data Science: A ModernDive into R and the Tidyverse [Second Edition]</a></em> by <a href="https://chester.rbind.io/">Chester Ismay</a>, <a href="https://rudeboybert.rbind.io/">Albert Y. Kim</a>, and <a href="https://avaldivi6.github.io/">Arturo Valdivia</a> licensed under <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a></p>
<p>Changes to the source material include addition of new material; light editing; rearranging, removing, and combining original material; adding and changing links; and adding first-person language from current author.</p>
<p>The resulting content is licensed under <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>.</p>
<section id="introduction" class="level2" data-number="27.1">
<h2 data-number="27.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">27.1</span> Introduction</h2>
<p>Now that we are equipped with skills for wrangling, tidying, and visualizing data, let’s proceed with data modeling. As I stated at the end of this week’s <em>understanding</em> reading, this walkthrough is going to repeat much of what we read there, though this focus on modeling—and practical <em>application</em> of data science—will give us a new way of thinking about it.</p>
<p>In this chapter, we work with <strong>regression</strong>, a method that helps us study the relationship between an <em>outcome variable</em> or <em>response</em> and one or more <em>explanatory variables</em> or <em>regressors</em>. The method starts by proposing a <em>statistical model</em>. Data is then collected and used to estimate the coefficients or parameters for the model, and these results are typically used for two purposes:</p>
<ol type="1">
<li>For <strong>explanation</strong> when we want to describe how changes in one or more of the regressors are associated with changes in the response, quantify those changes, establish which of the regressors truly have an association with the response, or determine whether the model used to describe the relationship between the response and the explanatory variables seems appropriate.</li>
<li>For <strong>prediction</strong> when we want to determine, based on the observed values of the regressors, what will the value of the response be? We are not concerned about how all the regressors relate and interact with one another or with the response, we simply want as good predictions as possible.</li>
</ol>
<p>As an illustration, assume that we want to study the relationship between blood pressure and potential risk factors such as daily salt intake, age, and physical activity levels. The response is blood pressure, and the regressors are the risk factors.</p>
<p>If we use linear regression for explanation, we may want to determine whether reducing daily salt intake has a real effect on lowering blood pressure, or by how much blood pressure decreases if an individual reduces their salt intake by half.</p>
<p>This information may help target individuals of a specific age group with advice on dietary changes to manage blood pressure.</p>
<p>On the other hand, if we use linear regression for prediction, we would like to determine, as accurately as possible, the blood pressure of a given individual based on the data collected about their salt intake, age, and physical activity levels. In this chapter, we will use linear regression for explanation.</p>
<p>The most basic and commonly-used type of regression is <em>linear regression</em>. Linear regression involves a <em>numerical</em> response and one or more regressors that can be <em>numerical</em> or <em>categorical</em>. It is called linear regression because the <strong>statistical model</strong> that describes the relationship between the expected response and the regressors is assumed to be linear. In particular, when the model has a single regressor, the linear regression is the equation of a line. Linear regression is the foundation for almost any other type of regression or related method.</p>
<p>We begin with regression with a single explanatory variable. We also introduce the <em>correlation coefficient</em>, discuss “correlation versus causation,” and determine whether the model <em>fits</em> the data observed.</p>
<section id="sec-reg-packages" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="sec-reg-packages">Needed packages</h3>
<p>load all the packages needed for this chapter (this assumes you’ve already installed them). In this chapter, we introduce some new packages:</p>
<ol type="1">
<li>The <code>tidyverse</code> “umbrella” package. Recall from our discussion in Section <a href="17_module_6_application.html#sec-tidyverse-package" class="quarto-xref"><span>Section 18.4</span></a> that loading the <code>tidyverse</code> package by running <code>library(tidyverse)</code> loads the following commonly used data science packages all at once:
<ul>
<li><code>ggplot2</code> for data visualization</li>
<li><code>dplyr</code> for data wrangling</li>
<li><code>tidyr</code> for converting data to “tidy” format</li>
<li><code>readr</code> for importing spreadsheet data into R</li>
<li>As well as the more advanced <code>purrr</code>, <code>tibble</code>, <code>stringr</code>, and <code>forcats</code> packages</li>
</ul></li>
<li>The <code>moderndive</code> package of datasets and functions for tidyverse-friendly introductory linear regression as well as a data frame summary function.</li>
</ol>
<p>If needed, read Section <a href="05_module_2_application.html#sec-packages" class="quarto-xref"><span>Section 6.3</span></a> for information on how to install and load R packages.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(moderndive)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="sec-model1" class="level2" data-number="27.2">
<h2 data-number="27.2" class="anchored" data-anchor-id="sec-model1"><span class="header-section-number">27.2</span> One numerical explanatory variable</h2>
<p>Before we introduce the model needed for simple linear regression, we present an example. Why do some countries exhibit high fertility rates while others have significantly lower ones? Are there correlations between fertility rates and life expectancy across different continents and nations? Could underlying socioeconomic factors be influencing these trends?</p>
<p>These are all questions that are of interest to demographers and policy makers, as understanding fertility rates is important for planning and development. By analyzing the dataset of UN member states, which includes variables such as country codes (ISO), fertility rates, and life expectancy for 2022, researchers can uncover patterns and make predictions about fertility rates based on life expectancy.</p>
<p>In this section, we aim to explain differences in fertility rates as a function of one numerical variable: life expectancy. Could it be that countries with higher life expectancy also have lower fertility rates? Could it be instead that countries with higher life expectancy tend to have higher fertility rates? Or could it be that there is no relationship between life expectancy and fertility rates? We answer these questions by modeling the relationship between fertility rates and life expectancy using <em>simple linear regression</em> where we have:</p>
<ol type="1">
<li>A numerical outcome variable <span class="math inline">\(y\)</span> (the country’s fertility rate) and</li>
<li>A single numerical explanatory variable <span class="math inline">\(x\)</span> (the country’s life expectancy).</li>
</ol>
<section id="sec-model1EDA" class="level3" data-number="27.2.1">
<h3 data-number="27.2.1" class="anchored" data-anchor-id="sec-model1EDA"><span class="header-section-number">27.2.1</span> Exploratory data analysis</h3>
<p>The data on the 193 current UN member states (as of 2024) can be found in the <code>un_member_states_2024</code> data frame included in the <code>moderndive</code> package. However, to keep things simple we include only those rows that don’t have missing data with <code>na.omit()</code> and <code>select()</code> only the subset of the variables we’ll consider in this chapter, and save this data in a new data frame called <code>UN_data_m9</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>UN_data_m9 <span class="ot">&lt;-</span> un_member_states_2024 <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(iso, </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">life_exp =</span> life_expectancy_2022, </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">fert_rate =</span> fertility_rate_2022, </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">obes_rate =</span> obesity_rate_2016)<span class="sc">|&gt;</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>A crucial step before doing any kind of analysis or modeling is performing an <em>exploratory data analysis</em>, or EDA for short. EDA gives you a sense of the distributions of the individual variables in your data, whether any potential relationships exist between variables, whether there are outliers and/or missing values, and (most importantly) how to build your model. Here are three common steps in an EDA:</p>
<ol type="1">
<li>Most crucially, looking at the raw data values.</li>
<li>Computing summary statistics, such as means, medians, and maximums.</li>
<li>Creating data visualizations.</li>
</ol>
<p>We perform the first common step in an exploratory data analysis: looking at the raw data values. Because this step seems so trivial, unfortunately many data analysts ignore it. However, getting an early sense of what your raw data looks like can often prevent many larger issues down the road.</p>
<p>You can do this by using RStudio’s spreadsheet viewer or by using the <code>glimpse()</code> function as introduced in Subsection <a href="05_module_2_application.html#sec-exploredataframes" class="quarto-xref"><span>Section 6.4.3</span></a> on exploring data frames:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(UN_data_m9)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 181
Columns: 4
$ iso       &lt;chr&gt; "AFG", "ALB", "DZA", "AGO", "ATG", "ARG", "ARM", "AUS", "AUT…
$ life_exp  &lt;dbl&gt; 53.6, 79.5, 78.0, 62.1, 77.8, 78.3, 76.1, 83.1, 82.3, 74.2, …
$ fert_rate &lt;dbl&gt; 4.3, 1.4, 2.7, 5.0, 1.6, 1.9, 1.6, 1.6, 1.5, 1.6, 1.4, 1.8, …
$ obes_rate &lt;dbl&gt; 5.5, 21.7, 27.4, 8.2, 18.9, 28.3, 20.2, 29.0, 20.1, 19.9, 31…</code></pre>
</div>
</div>
<p>Observe that <code>Rows: 181</code> indicates that there are 181 rows/observations in <code>UN_data_m9</code> after filtering out the missing values, where each row corresponds to one observed country/member state. It is important to note that the <em>observational unit</em> is an individual country. Recall from Subsection <a href="05_module_2_application.html#sec-exploredataframes" class="quarto-xref"><span>Section 6.4.3</span></a> that the observational unit is the “type of thing” that is being measured by our variables.</p>
<p>A full description of all the variables included in <code>un_member_states_2024</code> can be found by reading the associated help file (run <a href="https://moderndive.github.io/moderndive/reference/un_member_states_2024.html"><code>?un_member_states_2024</code></a> in the console). Let’s describe only the 4 variables we selected in <code>UN_data_m9</code>:</p>
<ol type="1">
<li><code>iso</code>: An identification variable used to distinguish between the 181 countries in the filtered dataset.</li>
<li><code>fert_rate</code>: A numerical variable representing the country’s fertility rate in 2022 corresponding to the expected number of children born per woman in child-bearing years. This is the outcome variable <span class="math inline">\(y\)</span> of interest.</li>
<li><code>life_exp</code>: A numerical variable representing the country’s average life expectancy in 2022 in years. This is the primary explanatory variable <span class="math inline">\(x\)</span> of interest.</li>
<li><code>obes_rate</code>: A numerical variable representing the country’s obesity rate in 2016. This will be another explanatory variable <span class="math inline">\(x\)</span> that we use in the <em>Learning check</em> at the end of this subsection.</li>
</ol>
<p>An alternative way to look at the raw data values is by choosing a random sample of the rows in <code>UN_data_m9</code> by piping it into the <code>slice_sample()</code> function from the <code>dplyr</code> package. Here we set the <code>n</code> argument to be <code>5</code>, indicating that we want a random sample of 5 rows. We display the results in Table <a href="#tbl-random-countries" class="quarto-xref">Table&nbsp;<span>27.1</span></a>. Note that due to the random nature of the sampling, you will likely end up with a different subset of 5 rows.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>UN_data_m9 <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-random-countries" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-random-countries-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;27.1: A random sample of 5 out of the 193 total countries (181 without missing data)
</figcaption>
<div aria-describedby="tbl-random-countries-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">iso</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">life_exp</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">fert_rate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">obes_rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PRT</td>
<td style="text-align: right;">81.5</td>
<td style="text-align: right;">1.4</td>
<td style="text-align: right;">20.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">MNE</td>
<td style="text-align: right;">77.8</td>
<td style="text-align: right;">1.7</td>
<td style="text-align: right;">23.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CPV</td>
<td style="text-align: right;">73.8</td>
<td style="text-align: right;">1.9</td>
<td style="text-align: right;">11.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">VNM</td>
<td style="text-align: right;">75.5</td>
<td style="text-align: right;">1.9</td>
<td style="text-align: right;">2.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IDN</td>
<td style="text-align: right;">73.1</td>
<td style="text-align: right;">2.1</td>
<td style="text-align: right;">6.9</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>We have looked at the raw values in our <code>UN_data_m9</code> data frame and got a preliminary sense of the data. We can now compute summary statistics. We start by computing the mean and median of our numerical outcome variable <code>fert_rate</code> and our numerical explanatory variable <code>life_exp</code>. We do this by using the <code>summarize()</code> function from <code>dplyr</code> along with the <code>mean()</code> and <code>median()</code> summary functions we saw in Section <a href="23_module_8_application.html#sec-summarize" class="quarto-xref"><span>Section 24.2</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>UN_data_m9 <span class="sc">|&gt;</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_life_exp =</span> <span class="fu">mean</span>(life_exp), </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">mean_fert_rate =</span> <span class="fu">mean</span>(fert_rate),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">median_life_exp =</span> <span class="fu">median</span>(life_exp), </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">median_fert_rate =</span> <span class="fu">median</span>(fert_rate))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">mean_life_exp</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean_fert_rate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">median_life_exp</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">median_fert_rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">73.6</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">75.1</td>
<td style="text-align: right;">2</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>However, what if we want other summary statistics as well, such as the standard deviation (a measure of spread), the minimum and maximum values, and various percentiles?</p>
<p>Typing all these summary statistic functions in <code>summarize()</code> would be long and tedious. Instead, we use the convenient <a href="https://moderndive.github.io/moderndive/reference/tidy_summary.html"><code>tidy_summary()</code></a> function in the <code>moderndive</code> package. This function takes in a data frame, summarizes it, and returns commonly used summary statistics in tidy format. We take our <code>UN_data_m9</code> data frame, <code>select()</code> only the outcome and explanatory variables <code>fert_rate</code> and <code>life_exp</code>, and pipe them into the <code>tidy_summary</code> function:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>UN_data_m9 <span class="sc">|&gt;</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(fert_rate, life_exp) <span class="sc">|&gt;</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy_summary</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">column</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">group</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">max</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">fert_rate</td>
<td style="text-align: right;">181</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">numeric</td>
<td style="text-align: right;">1.1</td>
<td style="text-align: right;">1.6</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">3.2</td>
<td style="text-align: right;">6.6</td>
<td style="text-align: right;">1.15</td>
</tr>
<tr class="even">
<td style="text-align: left;">life_exp</td>
<td style="text-align: right;">181</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">numeric</td>
<td style="text-align: right;">53.6</td>
<td style="text-align: right;">69.4</td>
<td style="text-align: right;">73.6</td>
<td style="text-align: right;">75.1</td>
<td style="text-align: right;">78.3</td>
<td style="text-align: right;">86.4</td>
<td style="text-align: right;">6.80</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We can also do this more directly by providing which <code>columns</code> we’d like a summary of inside the <code>tidy_summary()</code> function:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>UN_data_m9 <span class="sc">|&gt;</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy_summary</span>(<span class="at">columns =</span> <span class="fu">c</span>(fert_rate, life_exp))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">column</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">group</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">max</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">fert_rate</td>
<td style="text-align: right;">181</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">numeric</td>
<td style="text-align: right;">1.1</td>
<td style="text-align: right;">1.6</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">3.2</td>
<td style="text-align: right;">6.6</td>
<td style="text-align: right;">1.15</td>
</tr>
<tr class="even">
<td style="text-align: left;">life_exp</td>
<td style="text-align: right;">181</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">numeric</td>
<td style="text-align: right;">53.6</td>
<td style="text-align: right;">69.4</td>
<td style="text-align: right;">73.6</td>
<td style="text-align: right;">75.1</td>
<td style="text-align: right;">78.3</td>
<td style="text-align: right;">86.4</td>
<td style="text-align: right;">6.80</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Both return the same results for the numerical variables <code>fert_rate</code> and <code>life_exp</code>:</p>
<ul>
<li><code>column</code>: the name of the column being summarized</li>
<li><code>n</code>: the number of non-missing values</li>
<li><code>group</code>: <code>NA</code> (missing) for numerical columns, but will break down a categorical variable into its levels</li>
<li><code>type</code>: which type of column is it (<code>numeric</code>, <code>character</code>, <code>factor</code>, or <code>logical</code>)</li>
<li><code>min</code>: the <em>minimum</em> value</li>
<li><code>Q1</code>: the 1st quartile: the value at which 25% of observations are smaller than it (the <em>25th percentile</em>)</li>
<li><code>mean</code>: the average value for measuring central tendency</li>
<li><code>median</code>: the 2nd quartile: the value at which 50% of observations are smaller than it (the <em>50th percentile</em>)</li>
<li><code>Q3</code>: the 3rd quartile: the value at which 75% of observations are smaller than it (the <em>75th percentile</em>)</li>
<li><code>max</code>: the <em>maximum</em> value</li>
<li><code>sd</code>: the standard deviation value for measuring spread</li>
</ul>
<p>Looking at this output, we can see how the values of both variables distribute. For example, the median fertility rate was 2, whereas the median life expectancy was 75.14 years. The middle 50% of fertility rates was between 1.6 and 3.2 (the first and third quartiles), and the middle 50% of life expectancies was from 69.36 to 78.31.</p>
<p>The <code>tidy_summary()</code> function only returns what are known as <em>univariate</em> summary statistics: functions that take a single variable and return some numerical summary of that variable. However, there also exist <em>bivariate</em> summary statistics: functions that take in two variables and return some summary of those two variables.</p>
<p>In particular, when the two variables are numerical, we can compute the <em>correlation coefficient</em>. Generally speaking, <em>coefficients</em> are quantitative expressions of a specific phenomenon. A <em>correlation coefficient</em> measures the <em>strength of the linear relationship between two numerical variables</em>. Its value goes from -1 and 1 where:</p>
<ul>
<li>-1 indicates a perfect <em>negative relationship</em>: As one variable increases, the value of the other variable tends to go down, following a straight line.</li>
<li>0 indicates no relationship: The values of both variables go up/down independently of each other.</li>
<li>+1 indicates a perfect <em>positive relationship</em>: As the value of one variable goes up, the value of the other variable tends to go up as well in a linear fashion.</li>
</ul>
<p>Figure <a href="#fig-correlation1" class="quarto-xref">Figure&nbsp;<span>27.1</span></a> gives examples of nine different correlation coefficient values for hypothetical numerical variables <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-correlation1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-correlation1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="26_module_9_application_files/figure-html/fig-correlation1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-correlation1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27.1: Nine different correlation coefficients.
</figcaption>
</figure>
</div>
</div>
</div>
<p>For example, observe in the top right plot that for a correlation coefficient of -0.75 there is a negative linear relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, but it is not as strong as the negative linear relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> when the correlation coefficient is -0.9 or -1.</p>
<p>The correlation coefficient can be computed using the <a href="https://moderndive.github.io/moderndive/reference/get_correlation.html"><code>get_correlation()</code></a> function in the <code>moderndive</code> package. In this case, the inputs to the function are the two numerical variables for which we want to calculate the correlation coefficient.</p>
<p>We put the name of the outcome variable on the left-hand side of the <code>~</code> “tilde” sign, while putting the name of the explanatory variable on the right-hand side. This is known as R’s <em>formula notation</em>. We will use this same “formula” syntax with regression later in this chapter.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>UN_data_m9 <span class="sc">|&gt;</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_correlation</span>(<span class="at">formula =</span> fert_rate <span class="sc">~</span> life_exp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
     cor
   &lt;dbl&gt;
1 -0.812</code></pre>
</div>
</div>
<p>An alternative way to compute correlation is to use the <code>cor()</code> summary function within a <code>summarize()</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>UN_data_m9 <span class="sc">|&gt;</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">correlation =</span> <span class="fu">cor</span>(fert_rate, life_exp))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>In our case, the correlation coefficient of -0.812 indicates that the relationship between fertility rate and life expectancy is “moderately negative.” There is a certain amount of subjectivity in interpreting correlation coefficients, especially those that are not close to the extreme values of -1, 0, and 1.</p>
<p>We now perform the last step in EDA: creating data visualizations. Since both the <code>fert_rate</code> and <code>life_exp</code> variables are numerical, a scatterplot is an appropriate graph to visualize this data. We do this using <code>geom_point()</code> and display the result in Figure <a href="#fig-numxplot1" class="quarto-xref">Figure&nbsp;<span>27.2</span></a>. Furthermore, we set the <code>alpha</code> value to <code>0.1</code> to check for any overplotting.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(UN_data_m9, </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> life_exp, <span class="at">y =</span> fert_rate)) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Life Expectancy"</span>, <span class="at">y =</span> <span class="st">"Fertility Rate"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-numxplot1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-numxplot1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="26_module_9_application_files/figure-html/fig-numxplot1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-numxplot1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27.2: Scatterplot of relationship of life expectancy and fertility rate.
</figcaption>
</figure>
</div>
</div>
</div>
<p>We do not see much for overplotting due to little to no overlap in the points. Most life expectancy entries appear to fall between 70 and 80 years, while most fertility rate entries fall between 1.5 and 3.5 births. Furthermore, while opinions may vary, it is our opinion that the relationship between fertility rate and life expectancy is “moderately negative.” This is consistent with our earlier computed correlation coefficient of -0.812.</p>
<p>We build on the scatterplot in Figure <a href="#fig-numxplot1" class="quarto-xref">Figure&nbsp;<span>27.2</span></a> by adding a “best-fitting” line: of all possible lines we can draw on this scatterplot, it is the line that “best” fits through the cloud of points. We do this by adding a new <code>geom_smooth(method = "lm", se = FALSE)</code> layer to the <code>ggplot()</code> code that created the scatterplot in Figure <a href="#fig-numxplot1" class="quarto-xref">Figure&nbsp;<span>27.2</span></a>. The <code>method = "lm"</code> argument sets the line to be a “<strong>l</strong>inear <strong>m</strong>odel.” The <code>se = FALSE</code> argument suppresses <em>standard error</em> uncertainty bars. (We’ll define the concept of <em>standard error</em> later.)</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(UN_data_m9, <span class="fu">aes</span>(<span class="at">x =</span> life_exp, <span class="at">y =</span> fert_rate)) <span class="sc">+</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Life Expectancy"</span>, </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Fertility Rate"</span>,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Relationship of life expectancy and fertility rate"</span>) <span class="sc">+</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-numxplot3" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-numxplot3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="26_module_9_application_files/figure-html/fig-numxplot3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-numxplot3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27.3: Scatterplot of life expectancy and fertility rate with regression line.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The line in the resulting Figure <a href="#fig-numxplot3" class="quarto-xref">Figure&nbsp;<span>27.3</span></a> is called a “regression line.” The regression line is a visual summary of the relationship between two numerical variables, in our case the outcome variable <code>fert_rate</code> and the explanatory variable <code>life_exp</code>. The negative slope of the blue line is consistent with our earlier observed correlation coefficient of -0.812 suggesting that there is a negative relationship between these two variables: as a country’s population has higher life expectancy it tends to have a lower fertility rate. We’ll see later, however, that while the correlation coefficient and the slope of a regression line always have the same sign (positive or negative), they typically do not have the same value.</p>
<p>Furthermore, a regression line is “best-fitting” in that it minimizes some mathematical criteria. We present these mathematical criteria in Subsection <a href="#sec-leastsquares" class="quarto-xref"><span>Section 27.4.2</span></a>, but we suggest you read this subsection only after first reading the rest of this section on regression with one numerical explanatory variable.</p>
</section>
<section id="sec-model1table" class="level3" data-number="27.2.2">
<h3 data-number="27.2.2" class="anchored" data-anchor-id="sec-model1table"><span class="header-section-number">27.2.2</span> Simple linear regression</h3>
<p>You may recall from secondary/high school algebra that the equation of a line is <span class="math inline">\(y = a + b\cdot x\)</span>. (Note that the <span class="math inline">\(\cdot\)</span> symbol is equivalent to the <span class="math inline">\(\times\)</span> “multiply by” mathematical symbol. We’ll use the <span class="math inline">\(\cdot\)</span> symbol in the rest of this book as it is more succinct.) It is defined by two coefficients <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>. The intercept coefficient <span class="math inline">\(a\)</span> is the value of <span class="math inline">\(y\)</span> when <span class="math inline">\(x = 0\)</span>. The slope coefficient <span class="math inline">\(b\)</span> for <span class="math inline">\(x\)</span> is the increase in <span class="math inline">\(y\)</span> for every increase of one in <span class="math inline">\(x\)</span>. This is also called the “rise over run.”</p>
<p>However, when defining a regression line like the one in Figure <a href="#fig-numxplot3" class="quarto-xref">Figure&nbsp;<span>27.3</span></a>, we use slightly different notation: the equation of the regression line is <span class="math inline">\(\widehat{y} = b_0 + b_1 \cdot x\)</span> . The intercept coefficient is <span class="math inline">\(b_0\)</span>, so <span class="math inline">\(b_0\)</span> is the value of <span class="math inline">\(\widehat{y}\)</span> when <span class="math inline">\(x = 0\)</span>. The slope coefficient for <span class="math inline">\(x\)</span> is <span class="math inline">\(b_1\)</span>, i.e., the increase in <span class="math inline">\(\widehat{y}\)</span> for every increase of one in <span class="math inline">\(x\)</span>. Why do we put a “hat” on top of the <span class="math inline">\(y\)</span>? It’s a form of notation commonly used in regression to indicate that we have a “fitted value,” or the value of <span class="math inline">\(y\)</span> on the regression line for a given <span class="math inline">\(x\)</span> value as discussed further in Subsection <a href="#sec-model1points" class="quarto-xref"><span>Section 27.2.3</span></a>.</p>
<p>We know that the regression line in Figure <a href="#fig-numxplot3" class="quarto-xref">Figure&nbsp;<span>27.3</span></a> has a negative slope <span class="math inline">\(b_1\)</span> corresponding to our explanatory <span class="math inline">\(x\)</span> variable <code>life_exp</code>. Why? Because as countries tend to have higher <code>life_exp</code> values, they tend to have lower <code>fert_rate</code> values. However, what is the numerical value of the slope <span class="math inline">\(b_1\)</span>? What about the intercept <span class="math inline">\(b_0\)</span>? We do not compute these two values by hand, but rather we use a computer!</p>
<p>We can obtain the values of the intercept <span class="math inline">\(b_0\)</span> and the slope for <code>life_exp</code> <span class="math inline">\(b_1\)</span> by outputting the <em>linear regression coefficients</em>. This is done in two steps:</p>
<ol type="1">
<li>We first “fit” the linear regression model using the <code>lm()</code> function and save it in <code>demographics_model</code>.</li>
<li>We get the regression coefficients by applying <code>coef()</code> to <code>demographics_model</code>.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit regression model:</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>demographics_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(fert_rate <span class="sc">~</span> life_exp, <span class="at">data =</span> UN_data_m9)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Get regression coefficients</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(demographics_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We first focus on interpreting the regression coefficients, and later revisit the code that produced it. The coefficients are the intercept <span class="math inline">\(b_0 = 12.599\)</span> and the slope <span class="math inline">\(b_1 = -0.137\)</span> for <code>life_exp</code>. Thus the equation of the regression line in Figure <a href="#fig-numxplot3" class="quarto-xref">Figure&nbsp;<span>27.3</span></a> follows:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{y} &amp;= b_0 + b_1 \cdot x\\
\widehat{\text{fertility}\_\text{rate}} &amp;= b_0 + b_{\text{life}\_\text{expectancy}} \cdot \text{life}\_\text{expectancy}\\
&amp;= 12.599 + (-0.137) \cdot \text{life}\_\text{expectancy}
\end{aligned}
\]</span></p>
<p>The intercept <span class="math inline">\(b_0\)</span> = 12.599 is the average fertility rate <span class="math inline">\(\widehat{y}\)</span> = <span class="math inline">\(\widehat{\text{fertility}\_\text{rate}}\)</span> for those countries that had a <code>life_exp</code> of 0. Or in graphical terms, where the line intersects the <span class="math inline">\(y\)</span> axis for <span class="math inline">\(x\)</span> = 0. Note, however, that while the intercept of the regression line has a mathematical interpretation, it has no <em>practical</em> interpretation here, since observing a <code>life_exp</code> of 0 is impossible. Furthermore, looking at the scatterplot with the regression line in Figure <a href="#fig-numxplot3" class="quarto-xref">Figure&nbsp;<span>27.3</span></a>, no countries had a life expectancy anywhere near 0.</p>
<p>Of greater interest is the slope <span class="math inline">\(b_{\text{life}\_\text{expectancy}}\)</span> for <code>life_exp</code> of -0.137. This summarizes the relationship between the fertility rate and life expectancy variables. Note that the sign is negative, suggesting a negative relationship between these two variables. This means countries with higher life expectancies tend to have lower fertility rates. Recall that the correlation coefficient is -0.812. They both have the same negative sign, but have a different value. Recall also that the correlation’s interpretation is the “strength of linear association.” The slope’s interpretation is a little different:</p>
<blockquote class="blockquote">
<p>For every increase of 1 unit in <code>life_exp</code>, there is an <em>associated</em> decrease of, <em>on average</em>, 0.137 units of <code>fert_rate</code>.</p>
</blockquote>
<p>We only state that there is an <em>associated</em> increase and not necessarily a <em>causal</em> increase. Perhaps it may not be that higher life expectancies directly cause lower fertility rates. Instead, wealthier countries could tend to have stronger educational backgrounds, improved health, a higher standard of living, and have lower fertility rates, while at the same time these wealthy countries also tend to have higher life expectancies. Just because two variables are strongly associated, it does not necessarily mean that one causes the other. This is summed up in the often-quoted phrase, “correlation is not necessarily causation.” We discuss this idea further in Subsection <a href="#sec-correlation-is-not-causation" class="quarto-xref"><span>Section 27.4.1</span></a>.</p>
<p>Furthermore, we say that this associated decrease is <em>on average</em> 0.137 units of <code>fert_rate</code>, because you might have two countries whose <code>life_exp</code> values differ by 1 unit, but their difference in fertility rates may not be exactly <span class="math inline">\(-0.137\)</span>. What the slope of <span class="math inline">\(-0.137\)</span> is saying is that across all possible countries, the <em>average</em> difference in fertility rate between two countries whose life expectancies differ by one is <span class="math inline">\(-0.137\)</span>.</p>
<p>Now that we have learned how to compute the equation for the regression line in Figure <a href="#fig-numxplot3" class="quarto-xref">Figure&nbsp;<span>27.3</span></a> using the model coefficient values and how to interpret the resulting intercept and slope, we revisit the code that generated these coefficients:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit regression model:</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>demographics_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(fert_rate <span class="sc">~</span> life_exp, <span class="at">data =</span> UN_data_m9)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Get regression coefficients:</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(demographics_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>First, we “fit” the linear regression model to the <code>data</code> using the <code>lm()</code> function and save this as <code>demographics_model</code>. When we say “fit,” we mean “find the best fitting line to this data.” <code>lm()</code> stands for “linear model” and is used as <code>lm(y ~ x, data = df_name)</code> where:</p>
<ul>
<li><code>y</code> is the outcome variable, followed by a tilde <code>~</code>. In our case, <code>y</code> is set to <code>fert_rate</code>.</li>
<li><code>x</code> is the explanatory variable. In our case, <code>x</code> is set to <code>life_exp</code>.</li>
<li>The combination of <code>y ~ x</code> is called a <em>model formula</em>. (Note the order of <code>y</code> and <code>x</code>.) In our case, the model formula is <code>fert_rate ~ life_exp</code>. We saw such model formulas earlier with the <a href="https://moderndive.github.io/moderndive/reference/get_correlation.html"><code>get_correlation()</code></a> function in Subsection <a href="#sec-model1EDA" class="quarto-xref"><span>Section 27.2.1</span></a>.</li>
<li><code>df_name</code> is the name of the data frame that contains the variables <code>y</code> and <code>x</code>. In our case, <code>data</code> is the <code>UN_data_m9</code> data frame.</li>
</ul>
<p>Second, we take the saved model in <code>demographics_model</code> and apply the <code>coef()</code> function to it to obtain the regression coefficients. This gives us the components of the regression equation line: the intercept <span class="math inline">\(b_0\)</span> and the slope <span class="math inline">\(b_1\)</span>.</p>
</section>
<section id="sec-model1points" class="level3" data-number="27.2.3">
<h3 data-number="27.2.3" class="anchored" data-anchor-id="sec-model1points"><span class="header-section-number">27.2.3</span> Observed/fitted values and residuals</h3>
<p>We just saw how to get the value of the intercept and the slope of a regression line from the output of the <code>coef()</code> function. Now instead say we want information on individual observations. For example, we focus on the 21st of the 181 countries in the <code>UN_data_m9</code> data frame in Table <a href="#tbl-country-21" class="quarto-xref">Table&nbsp;<span>27.2</span></a>. This corresponds to the UN member state of Bosnia and Herzegovina (BIH).</p>
<div class="cell" data-layout-align="center">
<div id="tbl-country-21" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-country-21-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;27.2: Data for the 21st country out of 193
</figcaption>
<div aria-describedby="tbl-country-21-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">iso</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">life_exp</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">fert_rate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">obes_rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">BIH</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: right;">17.9</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>What is the value <span class="math inline">\(\widehat{y}\)</span> on the regression line corresponding to this country’s <code>life_exp</code> value of 77.98? In Figure <a href="#fig-numxplot4" class="quarto-xref">Figure&nbsp;<span>27.4</span></a> we mark three values corresponding to these results for Bosnia and Herzegovina and give their statistical names:</p>
<ul>
<li>Circle: The <em>observed value</em> <span class="math inline">\(y\)</span> = 1.3 is this country’s actual fertility rate.</li>
<li>Square: The <em>fitted value</em> <span class="math inline">\(\widehat{y}\)</span> is the value on the regression line for <span class="math inline">\(x =  \texttt{life\_exp} = 77.98\)</span>, computed with the intercept and slope in the previous regression table:</li>
</ul>
<p><span class="math display">\[\widehat{y} = b_0 + b_1 \cdot x = 12.599 + (-0.137) \cdot 77.98 = 1.894\]</span> * Arrow: The length of this arrow is the <em>residual</em> and is computed by subtracting the fitted value <span class="math inline">\(\widehat{y}\)</span> from the observed value <span class="math inline">\(y\)</span>. The residual can be thought of as a model’s error or “lack of fit” for a particular observation. In the case of this country, it is <span class="math inline">\(y - \widehat{y} = 1.3 - 1.894 = -0.594\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-numxplot4" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-numxplot4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="26_module_9_application_files/figure-html/fig-numxplot4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-numxplot4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27.4: Example of observed value, fitted value, and residual.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Now say we want to compute both the fitted value <span class="math inline">\(\widehat{y} = b_0 + b_1 \cdot x\)</span> and the residual <span class="math inline">\(y - \widehat{y}\)</span> for <em>all</em> 181 UN member states with complete data as of 2024. Recall that each country corresponds to one of the 181 rows in the <code>UN_data_m9</code> data frame and also one of the 181 points in the regression plot in Figure <a href="#fig-numxplot4" class="quarto-xref">Figure&nbsp;<span>27.4</span></a>.</p>
<p>We could repeat the previous calculations we performed by hand 181 times, but that would be tedious and time consuming. Instead, we use a computer with the <code>get_regression_points()</code> function. We apply the <code>get_regression_points()</code> function to <code>demographics_model</code>, which is where we saved our <code>lm()</code> model in the previous section. In Table <a href="#tbl-regression-points-1" class="quarto-xref">Table&nbsp;<span>27.3</span></a> we present the results of only the 21st through 24th courses for brevity.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>regression_points <span class="ot">&lt;-</span> <span class="fu">get_regression_points</span>(demographics_model)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>regression_points</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-regression-points-1" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-regression-points-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;27.3: Regression points (for only the 21st through 24th countries)
</figcaption>
<div aria-describedby="tbl-regression-points-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">ID</th>
<th style="text-align: right;">fert_rate</th>
<th style="text-align: right;">life_exp</th>
<th style="text-align: right;">fert_rate_hat</th>
<th style="text-align: right;">residual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">21</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: right;">78.0</td>
<td style="text-align: right;">1.89</td>
<td style="text-align: right;">-0.594</td>
</tr>
<tr class="even">
<td style="text-align: right;">22</td>
<td style="text-align: right;">2.7</td>
<td style="text-align: right;">65.6</td>
<td style="text-align: right;">3.59</td>
<td style="text-align: right;">-0.888</td>
</tr>
<tr class="odd">
<td style="text-align: right;">23</td>
<td style="text-align: right;">1.6</td>
<td style="text-align: right;">75.9</td>
<td style="text-align: right;">2.18</td>
<td style="text-align: right;">-0.576</td>
</tr>
<tr class="even">
<td style="text-align: right;">24</td>
<td style="text-align: right;">1.7</td>
<td style="text-align: right;">80.6</td>
<td style="text-align: right;">1.53</td>
<td style="text-align: right;">0.165</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>This function is an example of what is known in computer programming as a <em>wrapper function</em>. It takes other pre-existing functions and “wraps” them into a single function that hides its inner workings. This concept is illustrated in Figure <a href="#fig-moderndive-figure-wrapper" class="quarto-xref">Figure&nbsp;<span>27.5</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-moderndive-figure-wrapper" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-moderndive-figure-wrapper-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/shutterstock/wrapper_function.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-moderndive-figure-wrapper-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27.5: The concept of a wrapper function.
</figcaption>
</figure>
</div>
</div>
</div>
<p>So all you need to worry about is what the inputs look like and what the outputs look like; you leave all the other details “under the hood of the car.” In our regression modeling example, the <code>get_regression_points()</code> function takes a saved <code>lm()</code> linear regression model as input and returns a data frame of the regression predictions as output. If you are interested in learning more about the <code>get_regression_points()</code> function’s inner workings, check out Subsection <a href="#sec-underthehood" class="quarto-xref"><span>Section 27.4.3</span></a>.</p>
<p>We inspect the individual columns and match them with the elements of Figure <a href="#fig-numxplot4" class="quarto-xref">Figure&nbsp;<span>27.4</span></a>:</p>
<ul>
<li>The <code>fert_rate</code> column represents the observed outcome variable <span class="math inline">\(y\)</span>. This is the y-position of the 181 black points.</li>
<li>The <code>life_exp</code> column represents the values of the explanatory variable <span class="math inline">\(x\)</span>. This is the x-position of the 181 black points.</li>
<li>The <code>fert_rate_hat</code> column represents the fitted values <span class="math inline">\(\widehat{y}\)</span>. This is the corresponding value on the regression line for the 181 <span class="math inline">\(x\)</span> values.</li>
<li>The <code>residual</code> column represents the residuals <span class="math inline">\(y - \widehat{y}\)</span>. This is the 181 vertical distances between the 181 black points and the regression line.</li>
</ul>
<p>Just as we did for the 21st country in the <code>UN_data_m9</code> dataset (in the first row of the table), we repeat the calculations for the 24th country (in the fourth row of Table <a href="#tbl-regression-points-1" class="quarto-xref">Table&nbsp;<span>27.3</span></a>). This corresponds to the country of Brunei (BRN):</p>
<ul>
<li><code>fert_rate</code> <span class="math inline">\(= 1.7\)</span> is the observed <code>fert_rate</code> <span class="math inline">\(y\)</span> for this country.</li>
<li><code>life_exp</code> <span class="math inline">\(= 80.590\)</span> is the value of the explanatory variable <code>life_exp</code> <span class="math inline">\(x\)</span> for Brunei.</li>
<li><code>fert_rate_hat</code> <span class="math inline">\(= 1.535 = 12.599 + (-0.137) \cdot 80.590\)</span> is the fitted value <span class="math inline">\(\widehat{y}\)</span> on the regression line for this country.</li>
<li><code>residual</code> <span class="math inline">\(= 0.165 = 1.7 - 1.535\)</span> is the value of the residual for this country. In other words, the model’s fitted value was off by 0.165 fertility rate units for Brunei.</li>
</ul>
<p>If you like, you can skip ahead to Subsection <a href="#sec-leastsquares" class="quarto-xref"><span>Section 27.4.2</span></a> to learn about the processes behind what makes “best-fitting” regression lines. As a primer, a “best-fitting” line refers to the line that minimizes the <em>sum of squared residuals</em> out of all possible lines we can draw through the points. In Section <a href="#sec-model2" class="quarto-xref"><span>Section 27.3</span></a>, we’ll discuss another common scenario of having a categorical explanatory variable and a numerical outcome variable.</p>
</section>
</section>
<section id="sec-model2" class="level2" data-number="27.3">
<h2 data-number="27.3" class="anchored" data-anchor-id="sec-model2"><span class="header-section-number">27.3</span> One categorical explanatory variable</h2>
<p>It is an unfortunate truth that life expectancy is not the same across all countries in the world. International development agencies are interested in studying these differences in life expectancy in the hopes of identifying where governments should allocate resources to address this problem. In this section, we explore differences in life expectancy in two ways:</p>
<ol type="1">
<li>Differences between continents: Are there significant differences in average life expectancy between the six populated continents of the world: Africa, North America, South America, Asia, Europe, and Oceania?</li>
<li>Differences within continents: How does life expectancy vary within the world’s five continents? For example, is the spread of life expectancy among the countries of Africa larger than the spread of life expectancy among the countries of Asia?</li>
</ol>
<p>To answer such questions, we use an updated version of the <code>gapminder</code> data frame we visualized in Figure <a href="20_module_7_application.html#fig-gapminder" class="quarto-xref">Figure&nbsp;<span>21.1</span></a> in Subsection <a href="20_module_7_application.html#sec-gapminder" class="quarto-xref"><span>Section 21.2.2</span></a> on the grammar of graphics. This updated <code>un_member_states_2024</code> data we saw earlier in this chapter. It is included in the <code>moderndive</code> package and has international development statistics such as life expectancy, GDP per capita, and population for 193 countries for years near 2024. We use this data for basic regression again, but now using an explanatory variable <span class="math inline">\(x\)</span> that is categorical, as opposed to the numerical explanatory variable model we used in the previous Section <a href="#sec-model1" class="quarto-xref"><span>Section 27.2</span></a>:</p>
<ol type="1">
<li>A numerical outcome variable <span class="math inline">\(y\)</span> (a country’s life expectancy) and</li>
<li>A single categorical explanatory variable <span class="math inline">\(x\)</span> (the continent that the country is a part of).</li>
</ol>
<p>When the explanatory variable <span class="math inline">\(x\)</span> is categorical, the concept of a “best-fitting” regression line is a little different than the one we saw previously in Section <a href="#sec-model1" class="quarto-xref"><span>Section 27.2</span></a> where the explanatory variable <span class="math inline">\(x\)</span> was numerical. We study these differences shortly in Subsection <a href="#sec-model2table" class="quarto-xref"><span>Section 27.3.2</span></a>, but first we conduct an exploratory data analysis.</p>
<section id="sec-model2EDA" class="level3" data-number="27.3.1">
<h3 data-number="27.3.1" class="anchored" data-anchor-id="sec-model2EDA"><span class="header-section-number">27.3.1</span> Exploratory data analysis</h3>
<p>The data on the 193 countries can be found in the <code>un_member_states_2024</code> data frame included in the <code>moderndive</code> package. However, to keep things simple, we <code>select()</code> only the subset of the variables we’ll consider in this chapter and focus only on rows where we have no missing values with <code>na.omit()</code>. We’ll save this data in a new data frame called <code>gapminder2022</code>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>gapminder2022 <span class="ot">&lt;-</span> un_member_states_2024 <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(country, <span class="at">life_exp =</span> life_expectancy_2022, continent, gdp_per_capita) <span class="sc">|&gt;</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We perform the first common step in an exploratory data analysis: looking at the raw data values. You can do this by using RStudio’s spreadsheet viewer or by using the <code>glimpse()</code> command as introduced in Subsection <a href="05_module_2_application.html#sec-exploredataframes" class="quarto-xref"><span>Section 6.4.3</span></a> on exploring data frames:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(gapminder2022)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 188
Columns: 4
$ country        &lt;chr&gt; "Afghanistan", "Albania", "Algeria", "Andorra", "Angola…
$ life_exp       &lt;dbl&gt; 53.6, 79.5, 78.0, 83.4, 62.1, 77.8, 78.3, 76.1, 83.1, 8…
$ continent      &lt;fct&gt; Asia, Europe, Africa, Europe, Africa, North America, So…
$ gdp_per_capita &lt;dbl&gt; 356, 6810, 4343, 41993, 3000, 19920, 13651, 7018, 65100…</code></pre>
</div>
</div>
<p>Observe that <code>Rows: 188</code> indicates that there are 188 rows/observations in <code>gapminder2022</code>, where each row corresponds to one country. In other words, the <em>observational unit</em> is an individual country. Furthermore, observe that the variable <code>continent</code> is of type <code>&lt;fct&gt;</code>, which stands for <em>factor</em>, which is R’s way of encoding categorical variables.</p>
<p>A full description of all the variables included in <code>un_member_states_2024</code> can be found by reading the associated help file (run <a href="https://moderndive.github.io/moderndive/reference/un_member_states_2024.html"><code>?un_member_states_2024</code></a> in the console). However, we fully describe only the 4 variables we selected in <code>gapminder2022</code>:</p>
<ol type="1">
<li><code>country</code>: An identification variable of type character/text used to distinguish the 188 countries in the dataset.</li>
<li><code>life_exp</code>: A numerical variable of that country’s life expectancy at birth. This is the outcome variable <span class="math inline">\(y\)</span> of interest.</li>
<li><code>continent</code>: A categorical variable with five levels. Here “levels” correspond to the possible categories: Africa, Asia, Americas, Europe, and Oceania. This is the explanatory variable <span class="math inline">\(x\)</span> of interest.</li>
<li><code>gdp_per_capita</code>: A numerical variable of that country’s GDP per capita in US inflation-adjusted dollars that we’ll use as another outcome variable <span class="math inline">\(y\)</span> in the <em>Learning check</em> at the end of this subsection.</li>
</ol>
<p>We next look at a random sample of three out of the 188 countries in Table <a href="#tbl-model2-data-preview" class="quarto-xref">Table&nbsp;<span>27.4</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>gapminder2022 <span class="sc">|&gt;</span> <span class="fu">sample_n</span>(<span class="at">size =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-model2-data-preview" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model2-data-preview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;27.4: Random sample of 3 out of 188 countries
</figcaption>
<div aria-describedby="tbl-model2-data-preview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">country</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">life_exp</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">continent</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">gdp_per_capita</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Panama</td>
<td style="text-align: right;">77.6</td>
<td style="text-align: left;">North America</td>
<td style="text-align: right;">17358</td>
</tr>
<tr class="even">
<td style="text-align: left;">Micronesia, Federated States of</td>
<td style="text-align: right;">74.4</td>
<td style="text-align: left;">Oceania</td>
<td style="text-align: right;">3714</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Burundi</td>
<td style="text-align: right;">67.4</td>
<td style="text-align: left;">Africa</td>
<td style="text-align: right;">259</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Random sampling will likely produce a different subset of 3 rows for you than what’s shown. Now that we have looked at the raw values in our <code>gapminder2022</code> data frame and got a sense of the data, we compute summary statistics. We again apply <code>tidy_summary()</code> from the <code>moderndive</code> package. Recall that this function takes in a data frame, summarizes it, and returns commonly used summary statistics. We take our <code>gapminder2022</code> data frame, <code>select()</code> only the outcome and explanatory variables <code>life_exp</code> and <code>continent</code>, and pipe them into <code>tidy_summary()</code> in Table <a href="#tbl-lifeexp-cont" class="quarto-xref">Table&nbsp;<span>27.5</span></a>:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>gapminder2022 <span class="sc">|&gt;</span> <span class="fu">select</span>(life_exp, continent) <span class="sc">|&gt;</span> <span class="fu">tidy_summary</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-lifeexp-cont" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-lifeexp-cont-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;27.5: Summary of life expectancy and continent variables
</figcaption>
<div aria-describedby="tbl-lifeexp-cont-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">column</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">group</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">max</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">life_exp</td>
<td style="text-align: right;">188</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">numeric</td>
<td style="text-align: right;">53.6</td>
<td style="text-align: right;">69.4</td>
<td style="text-align: right;">73.8</td>
<td style="text-align: right;">75.2</td>
<td style="text-align: right;">78.4</td>
<td style="text-align: right;">89.6</td>
<td style="text-align: right;">6.93</td>
</tr>
<tr class="even">
<td style="text-align: left;">continent</td>
<td style="text-align: right;">52</td>
<td style="text-align: left;">Africa</td>
<td style="text-align: left;">factor</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">continent</td>
<td style="text-align: right;">44</td>
<td style="text-align: left;">Asia</td>
<td style="text-align: left;">factor</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">continent</td>
<td style="text-align: right;">43</td>
<td style="text-align: left;">Europe</td>
<td style="text-align: left;">factor</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">continent</td>
<td style="text-align: right;">23</td>
<td style="text-align: left;">North America</td>
<td style="text-align: left;">factor</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">continent</td>
<td style="text-align: right;">14</td>
<td style="text-align: left;">Oceania</td>
<td style="text-align: left;">factor</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">continent</td>
<td style="text-align: right;">12</td>
<td style="text-align: left;">South America</td>
<td style="text-align: left;">factor</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The <code>tidy_summary()</code> output now reports summaries for categorical variables and for the numerical variables we reviewed before. Let’s focus just on discussing the results for the categorical <code>factor</code> variable <code>continent</code>:</p>
<ul>
<li><code>n</code>: The number of non-missing entries for each group</li>
<li><code>group</code>: Breaks down a categorical variable into its unique levels. For this variable, it is corresponding to Africa, Asia, North and South America, Europe, and Oceania.</li>
<li><code>type</code>: The data type of the variable. Here, it is a <code>factor</code>.</li>
<li><code>min</code> to <code>sd</code>: These are missing since calculating the five-number summary, the mean, and standard deviation for categorical variables doesn’t make sense.</li>
</ul>
<p>Turning our attention to the summary statistics of the numerical variable <code>life_exp</code>, we observe that the global median life expectancy in 2022 was 75.14. Thus, half of the world’s countries (96 countries) had a life expectancy of less than 75.14. The mean life expectancy of 73.55 is lower, however. Why is the mean life expectancy lower than the median?</p>
<p>We can answer this question by performing the last of the three common steps in an exploratory data analysis: creating data visualizations. We visualize the distribution of our outcome variable <span class="math inline">\(y\)</span> = <code>life_exp</code> in Figure <a href="#fig-lifeexp2022hist" class="quarto-xref">Figure&nbsp;<span>27.6</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gapminder2022, <span class="fu">aes</span>(<span class="at">x =</span> life_exp)) <span class="sc">+</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Life expectancy"</span>, </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of countries"</span>,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Histogram of distribution of worldwide life expectancies"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-lifeexp2022hist" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lifeexp2022hist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="26_module_9_application_files/figure-html/fig-lifeexp2022hist-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lifeexp2022hist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27.6: Histogram of life expectancy in 2022.
</figcaption>
</figure>
</div>
</div>
</div>
<p>We see that this data is <em>left-skewed</em>, also known as <em>negatively</em> skewed: there are a few countries with low life expectancy that are bringing down the mean life expectancy. However, the median is less sensitive to the effects of such outliers; hence, the median is greater than the mean in this case.</p>
<p>Remember, however, that we want to compare life expectancies both between continents and within continents. In other words, our visualizations need to incorporate some notion of the variable <code>continent</code>. We can do this easily with a faceted histogram. Recall from Section <a href="20_module_7_application.html#sec-facets" class="quarto-xref"><span>Section 21.6</span></a> that facets allow us to split a visualization by the different values of another variable. We display the resulting visualization in Figure <a href="#fig-catxplot0b" class="quarto-xref">Figure&nbsp;<span>27.7</span></a> by adding a <code>facet_wrap(~ continent, nrow = 2)</code> layer.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gapminder2022, <span class="fu">aes</span>(<span class="at">x =</span> life_exp)) <span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Life expectancy"</span>, </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of countries"</span>,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Histogram of distribution of worldwide life expectancies"</span>) <span class="sc">+</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> continent, <span class="at">nrow =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-catxplot0b" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-catxplot0b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="26_module_9_application_files/figure-html/fig-catxplot0b-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-catxplot0b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27.7: Life expectancy in 2022 by continent (faceted).
</figcaption>
</figure>
</div>
</div>
</div>
<p>Observe that unfortunately the distribution of African life expectancies is much lower than the other continents. In Europe, life expectancies tend to be higher and furthermore do not vary as much. On the other hand, both Asia and Africa have the most variation in life expectancies.</p>
<p>Recall that an alternative method to visualize the distribution of a numerical variable split by a categorical variable is by using a side-by-side boxplot. We map the categorical variable <code>continent</code> to the <span class="math inline">\(x\)</span>-axis and the different life expectancies within each continent on the <span class="math inline">\(y\)</span>-axis in Figure <a href="#fig-catxplot1" class="quarto-xref">Figure&nbsp;<span>27.8</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gapminder2022, <span class="fu">aes</span>(<span class="at">x =</span> continent, <span class="at">y =</span> life_exp)) <span class="sc">+</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Continent"</span>, <span class="at">y =</span> <span class="st">"Life expectancy"</span>,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Life expectancy by continent"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-catxplot1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-catxplot1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="26_module_9_application_files/figure-html/fig-catxplot1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-catxplot1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27.8: Life expectancy in 2022 by continent (boxplot).
</figcaption>
</figure>
</div>
</div>
</div>
<p>Some people prefer comparing the distributions of a numerical variable between different levels of a categorical variable using a boxplot instead of a faceted histogram. This is because we can make quick comparisons between the categorical variable’s levels with imaginary horizontal lines. For example, observe in Figure <a href="#fig-catxplot1" class="quarto-xref">Figure&nbsp;<span>27.8</span></a> that we can quickly convince ourselves that Europe has the highest median life expectancies by drawing an imaginary horizontal line near <span class="math inline">\(y = 81\)</span>. Furthermore, as we observed in the faceted histogram in Figure <a href="#fig-catxplot0b" class="quarto-xref">Figure&nbsp;<span>27.7</span></a>, Africa and Asia have the largest variation in life expectancy as evidenced by their large interquartile ranges (the size of the boxes).</p>
<p>It’s important to remember, however, that the solid lines in the middle of the boxes correspond to the medians (the middle value) rather than the mean (the average). So, for example, if you look at Asia, the solid line denotes the median life expectancy of around 75 years. This tells us that half of all countries in Asia have a life expectancy below 75 years, whereas half have a life expectancy above 75 years. We compute the median and mean life expectancy for each continent with a little more data wrangling and display the results in Table <a href="#tbl-catxplot0" class="quarto-xref">Table&nbsp;<span>27.6</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>life_exp_by_continent <span class="ot">&lt;-</span> gapminder2022 <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(continent) <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">median =</span> <span class="fu">median</span>(life_exp), <span class="at">mean =</span> <span class="fu">mean</span>(life_exp))</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>life_exp_by_continent</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-catxplot0" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-catxplot0-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;27.6: Life expectancy by continent
</figcaption>
<div aria-describedby="tbl-catxplot0-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">continent</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Africa</td>
<td style="text-align: right;">66.1</td>
<td style="text-align: right;">66.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Asia</td>
<td style="text-align: right;">75.4</td>
<td style="text-align: right;">75.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Europe</td>
<td style="text-align: right;">81.5</td>
<td style="text-align: right;">79.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">North America</td>
<td style="text-align: right;">76.1</td>
<td style="text-align: right;">76.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oceania</td>
<td style="text-align: right;">74.6</td>
<td style="text-align: right;">74.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">South America</td>
<td style="text-align: right;">75.4</td>
<td style="text-align: right;">75.2</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Observe the order of the second column <code>median</code> life expectancy: Africa is lowest, Europe the highest, and the others have similar medians between Africa and Europe. This ordering corresponds to the ordering of the solid black lines inside the boxes in our side-by-side boxplot in Figure <a href="#fig-catxplot1" class="quarto-xref">Figure&nbsp;<span>27.8</span></a>.</p>
<p>We now turn our attention to the values in the third column <code>mean</code>. Using Africa’s mean life expectancy of 66.31 as a <em>baseline for comparison</em>, we start making comparisons to the mean life expectancies of the other four continents and put these values in Table <a href="#tbl-continent-mean-life-expectancies" class="quarto-xref">Table&nbsp;<span>27.7</span></a>, which we’ll revisit later on in this section.</p>
<ol type="1">
<li>For Asia, it is 74.95 - 66.31 = 8.64 years higher.</li>
<li>For Europe, it is 79.91 - 66.31 = 13.6 years higher.</li>
<li>For North America, it is 76.29 - 66.31 = 9.98 years higher.</li>
<li>For Oceania, it is 74.42 - 66.31 = 8.11 years higher.</li>
<li>For South America, it is 75.23 - 66.31 = 8.92 years higher.</li>
</ol>
<div class="cell" data-layout-align="center">
<div id="tbl-continent-mean-life-expectancies" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-continent-mean-life-expectancies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;27.7: Mean life expectancy by continent and relative differences from mean for Africa
</figcaption>
<div aria-describedby="tbl-continent-mean-life-expectancies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">continent</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference versus Africa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Africa</td>
<td style="text-align: right;">66.3</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Asia</td>
<td style="text-align: right;">75.0</td>
<td style="text-align: right;">8.64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Europe</td>
<td style="text-align: right;">79.9</td>
<td style="text-align: right;">13.60</td>
</tr>
<tr class="even">
<td style="text-align: left;">North America</td>
<td style="text-align: right;">76.3</td>
<td style="text-align: right;">9.99</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oceania</td>
<td style="text-align: right;">74.4</td>
<td style="text-align: right;">8.11</td>
</tr>
<tr class="even">
<td style="text-align: left;">South America</td>
<td style="text-align: right;">75.2</td>
<td style="text-align: right;">8.92</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="sec-model2table" class="level3" data-number="27.3.2">
<h3 data-number="27.3.2" class="anchored" data-anchor-id="sec-model2table"><span class="header-section-number">27.3.2</span> Linear regression</h3>
<p>In Subsection <a href="#sec-model1table" class="quarto-xref"><span>Section 27.2.2</span></a> we introduced simple linear regression, which involves modeling the relationship between a numerical outcome variable <span class="math inline">\(y\)</span> and a numerical explanatory variable <span class="math inline">\(x\)</span>. In our life expectancy example, we now instead have a categorical explanatory variable <code>continent</code>. Our model will not yield a “best-fitting” regression line like in Figure <a href="#fig-numxplot3" class="quarto-xref">Figure&nbsp;<span>27.3</span></a>, but rather <em>offsets</em> relative to a baseline for comparison.</p>
<p>As we did in Subsection <a href="#sec-model1table" class="quarto-xref"><span>Section 27.2.2</span></a> when studying the relationship between fertility rates and life expectancy, we output the regression coefficients for this model. Recall that this is done in two steps:</p>
<ol type="1">
<li>We “fit” the linear regression model using <code>lm(y ~ x, data)</code> and save it in <code>life_exp_model</code>.</li>
<li>We get the regression coefficients by applying the <code>coef()</code> function to <code>life_exp_model</code>.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>life_exp_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(life_exp <span class="sc">~</span> continent, <span class="at">data =</span> gapminder2022)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(life_exp_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           (Intercept)          continentAsia        continentEurope 
                 66.31                   8.64                  13.60 
continentNorth America       continentOceania continentSouth America 
                  9.99                   8.11                   8.92 </code></pre>
</div>
</div>
<p>We once again focus on the values in these coefficient values. Why are there now 6 entries? We break them down one by one:</p>
<ol type="1">
<li><p><code>intercept</code> corresponds to the mean life expectancy of countries in Africa of 66.31 years.</p></li>
<li><p><code>continentAsia</code> corresponds to countries in Asia and the value +8.64 is the same difference in mean life expectancy relative to Africa we displayed in Table <a href="#tbl-continent-mean-life-expectancies" class="quarto-xref">Table&nbsp;<span>27.7</span></a>. In other words, the mean life expectancy of countries in Asia is <span class="math inline">\(66.31 + 8.64 = 74.95\)</span>.</p></li>
<li><p><code>continentEurope</code> corresponds to countries in Europe and the value +13.6 is the same difference in mean life expectancy relative to Africa we displayed in Table <a href="#tbl-continent-mean-life-expectancies" class="quarto-xref">Table&nbsp;<span>27.7</span></a>. In other words, the mean life expectancy of countries in Europe is <span class="math inline">\(66.31 + 13.6 = 79.91\)</span>.</p></li>
<li><p><code>continentNorth America</code> corresponds to countries in North America and the value +9.98 is the same difference in mean life expectancy relative to Africa we displayed in Table <a href="#tbl-continent-mean-life-expectancies" class="quarto-xref">Table&nbsp;<span>27.7</span></a>. In other words, the mean life expectancy of countries in North America is <span class="math inline">\(66.31 + 9.98 = 76.29\)</span>.</p></li>
<li><p><code>continentOceania</code> corresponds to countries in Oceania and the value +8.11 is the same difference in mean life expectancy relative to Africa we displayed in Table <a href="#tbl-continent-mean-life-expectancies" class="quarto-xref">Table&nbsp;<span>27.7</span></a>. In other words, the mean life expectancy of countries in Oceania is <span class="math inline">\(66.31 + 8.11 = 74.42\)</span>.</p></li>
<li><p><code>continentSouth America</code> corresponds to countries in South America and the value +8.92 is the same difference in mean life expectancy relative to Africa we displayed in Table <a href="#tbl-continent-mean-life-expectancies" class="quarto-xref">Table&nbsp;<span>27.7</span></a>. In other words, the mean life expectancy of countries in South America is <span class="math inline">\(66.31 + 8.92 = 75.23\)</span>.</p></li>
</ol>
<p>To summarize, the 6 values for the regression coefficients correspond to the “baseline for comparison” continent Africa (the intercept) as well as five “offsets” from this baseline for the remaining 5 continents: Asia, Europe, North America, Oceania, and South America.</p>
<p>You might be asking at this point why was Africa chosen as the “baseline for comparison” group. This is the case for no other reason than it comes first alphabetically of the six continents; by default R arranges factors/categorical variables in alphanumeric order. You can change this baseline group to be another continent if you manipulate the variable <code>continent</code>’s factor “levels” using the <code>forcats</code> package. See <a href="https://r4ds.had.co.nz/factors.html">Chapter 15</a> of <em>R for Data Science</em> for examples.</p>
<p>We now write the equation for our fitted values <span class="math inline">\(\widehat{y} = \widehat{\text{life exp}}\)</span>.</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{y} = \widehat{\text{life exp}} &amp;= b_0 + b_{\text{Asia}}\cdot\mathbb{1}_{\text{Asia}}(x) + b_{\text{Europe}}\cdot\mathbb{1}_{\text{Europe}}(x) \\
&amp; \qquad + b_{\text{North America}}\cdot\mathbb{1}_{\text{North America}}(x) + b_{\text{Oceania}}\cdot\mathbb{1}_{\text{Oceania }}(x) \\
&amp; \qquad + b_{\text{South America}}\cdot\mathbb{1}_{\text{South America}}(x)\\
&amp;= 66.31 + 8.64\cdot\mathbb{1}_{\text{Asia}}(x) + 13.6\cdot\mathbb{1}_{\text{Euro}}(x)  \\
&amp; \qquad + 9.98\cdot\mathbb{1}_{\text{North America}}(x) + 8.11\cdot\mathbb{1}_{\text{Oceania}}(x) \\
&amp; \qquad + 8.92\cdot\mathbb{1}_{\text{South America}}(x)
\end{aligned}
\]</span></p>
<p>Whoa! That looks daunting! Don’t fret, however, as once you understand what all the elements mean, things simplify greatly. First, <span class="math inline">\(\mathbb{1}_{A}(x)\)</span> is what’s known in mathematics as an “indicator function.” It returns only one of two possible values, 0 and 1, where</p>
<p><span class="math display">\[
\mathbb{1}_{A}(x) = \left\{
\begin{array}{ll}
1 &amp; \text{if } x \text{ is in } A \\
0 &amp; \text{if } \text{otherwise} \end{array}
\right.
\]</span></p>
<p>In a statistical modeling context, this is also known as a <em>dummy variable</em>. In our case, we consider the first such indicator variable <span class="math inline">\(\mathbb{1}_{\text{Amer}}(x)\)</span>. This indicator function returns 1 if a country is in the Asia, 0 otherwise:</p>
<p><span class="math display">\[
\mathbb{1}_{\text{Amer}}(x) = \left\{
\begin{array}{ll}
1 &amp; \text{if } \text{country } x \text{ is in Asia} \\
0 &amp; \text{otherwise}\end{array}
\right.
\]</span></p>
<p>Second, <span class="math inline">\(b_0\)</span> corresponds to the intercept as before; in this case, it is the mean life expectancy of all countries in Africa. Third, the <span class="math inline">\(b_{\text{Asia}}\)</span>, <span class="math inline">\(b_{\text{Europe}}\)</span>, <span class="math inline">\(b_{\text{North America}}\)</span>, <span class="math inline">\(b_{\text{Oceania}}\)</span>, and <span class="math inline">\(b_{\text{South America}}\)</span> represent the 5 “offsets relative to the baseline for comparison” in the regression coefficients.</p>
<p>We put this all together and compute the fitted value <span class="math inline">\(\widehat{y} = \widehat{\text{life exp}}\)</span> for a country in Africa. Since the country is in Africa, all five indicator functions <span class="math inline">\(\mathbb{1}_{\text{Asia}}(x)\)</span>, <span class="math inline">\(\mathbb{1}_{\text{Europe}}(x)\)</span>, <span class="math inline">\(\mathbb{1}_{\text{North America}}(x)\)</span>, <span class="math inline">\(\mathbb{1}_{\text{Oceania}}(x)\)</span>, and <span class="math inline">\(\mathbb{1}_{\text{South America}}(x)\)</span> will equal 0, and thus:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{\text{life exp}} &amp;= b_0 + b_{\text{Asia}}\cdot\mathbb{1}_{\text{Asia}}(x)
+ b_{\text{Europe}}\cdot\mathbb{1}_{\text{Europe}}(x) \\
&amp; \qquad  + b_{\text{North America}}\cdot\mathbb{1}_{\text{North America}}(x) +  b_{\text{Oceania}}\cdot\mathbb{1}_{\text{Oceania}}(x) \\
&amp; \qquad + b_{\text{South America}}\cdot\mathbb{1}_{\text{South America}}(x) \\
&amp;= 66.31 + 8.64\cdot\mathbb{1}_{\text{Asia}}(x)
+ 13.6\cdot\mathbb{1}_{\text{Europe}}(x)\\
&amp; \qquad + 9.98\cdot\mathbb{1}_{\text{North America}}(x) + 8.11\cdot\mathbb{1}_{\text{Oceania}}(x) \\
&amp; \qquad + 8.92\cdot\mathbb{1}_{\text{South America}}(x)\\
&amp;= 66.31 + 8.64\cdot 0 + 13.6\cdot 0 + 9.98\cdot 0 + 8.11\cdot 0 + 8.92\cdot 0\\
&amp;= 66.31
\end{aligned}
\]</span></p>
<p>In other words, all that is left is the intercept <span class="math inline">\(b_0\)</span>, corresponding to the average life expectancy of African countries of 66.31 years. Next, say we are considering a country in Asia. In this case, only the indicator function <span class="math inline">\(\mathbb{1}_{\text{Asia}}(x)\)</span> for Asia will equal 1, while all the others will equal 0, and thus:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{\text{life exp}} &amp;= b_0 + b_{\text{Asia}}\cdot\mathbb{1}_{\text{Asia}}(x)
+ b_{\text{Europe}}\cdot\mathbb{1}_{\text{Europe}}(x)\\
&amp; \qquad + b_{\text{North America}}\cdot\mathbb{1}_{\text{North America}}(x) +  b_{\text{Oceania}}\cdot\mathbb{1}_{\text{Oceania}}(x) \\
&amp; \qquad + b_{\text{South America}}\cdot\mathbb{1}_{\text{South America}}(x) \\
&amp;= 66.31 + 8.64\cdot\mathbb{1}_{\text{Asia}}(x)
+ 13.6\cdot\mathbb{1}_{\text{Europe}}(x) \\
&amp; \qquad + 9.98\cdot\mathbb{1}_{\text{North America}}(x) + 8.11\cdot\mathbb{1}_{\text{Oceania}}(x) \\
&amp; \qquad + 8.92\cdot\mathbb{1}_{\text{South America}}(x)\\
&amp;= 66.31 + 8.64\cdot 1 + 13.6\cdot 0 + 9.98\cdot 0 + 8.11\cdot 0 + 8.92\cdot 0\\
&amp;= 66.31 + 8.64 \\
&amp; = 74.95
\end{aligned}
\]</span></p>
<p>which is the mean life expectancy for countries in Asia of 74.95 years in Table <a href="#tbl-continent-mean-life-expectancies" class="quarto-xref">Table&nbsp;<span>27.7</span></a>. Note the “offset from the baseline for comparison” is +8.64 years.</p>
<p>We do one more. Say we are considering a country in South America. In this case, only the indicator function <span class="math inline">\(\mathbb{1}_{\text{South America}}(x)\)</span> for South America will equal 1, while all the others will equal 0, and thus:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{\text{life exp}} &amp;= b_0 + b_{\text{Asia}}\cdot\mathbb{1}_{\text{Asia}}(x)
+ b_{\text{Europe}}\cdot\mathbb{1}_{\text{Europe}}(x) \\
&amp; \qquad + b_{\text{North America}}\cdot\mathbb{1}_{\text{North America}}(x) +  b_{\text{Oceania}}\cdot\mathbb{1}_{\text{Oceania}}(x) \\
&amp; \qquad + b_{\text{South America}}\cdot\mathbb{1}_{\text{South America}}(x) \\
&amp;= 66.31 + 8.64\cdot\mathbb{1}_{\text{Asia}}(x)
+ 13.6\cdot\mathbb{1}_{\text{Europe}}(x)\\
&amp; \qquad + 9.98\cdot\mathbb{1}_{\text{North America}}(x) + 8.11\cdot\mathbb{1}_{\text{Oceania}}(x) + 8.92\cdot\mathbb{1}_{\text{South America}}(x)\\
&amp;= 66.31 + 8.64\cdot 0 + 13.6\cdot 0 + 9.98\cdot 0 + 8.11\cdot 0 + 8.92\cdot 1\\
&amp;= 66.31 + 8.92 \\
&amp; = 75.23
\end{aligned}
\]</span></p>
<p>which is the mean life expectancy for South American countries of 75.23 years in Table <a href="#tbl-continent-mean-life-expectancies" class="quarto-xref">Table&nbsp;<span>27.7</span></a>. The “offset from the baseline for comparison” here is +8.64 years.</p>
<p>We generalize this idea a bit. If we fit a linear regression model using a categorical explanatory variable <span class="math inline">\(x\)</span> that has <span class="math inline">\(k\)</span> possible categories, the regression table will return an intercept and <span class="math inline">\(k - 1\)</span> “offsets.” In our case, since there are <span class="math inline">\(k = 6\)</span> continents, the regression model returns an intercept corresponding to the baseline for comparison group of Africa and <span class="math inline">\(k - 1 = 5\)</span> offsets corresponding to Asia, Europe, North America, Oceania, and South America.</p>
<p>Understanding a regression table output when you are using a categorical explanatory variable is a topic those new to regression often struggle with. The only real remedy for these struggles is practice, practice, practice. However, once you equip yourselves with an understanding of how to create regression models using categorical explanatory variables, you’ll be able to incorporate many new variables into your models, given the large amount of the world’s data that is categorical.</p>
</section>
<section id="sec-model2points" class="level3" data-number="27.3.3">
<h3 data-number="27.3.3" class="anchored" data-anchor-id="sec-model2points"><span class="header-section-number">27.3.3</span> Observed/fitted values and residuals</h3>
<p>Recall in Subsection <a href="#sec-model1points" class="quarto-xref"><span>Section 27.2.3</span></a>, we defined the following three concepts:</p>
<ol type="1">
<li>Observed values <span class="math inline">\(y\)</span>, or the observed value of the outcome variable </li>
<li>Fitted values <span class="math inline">\(\widehat{y}\)</span>, or the value on the regression line for a given <span class="math inline">\(x\)</span> value</li>
<li>Residuals <span class="math inline">\(y - \widehat{y}\)</span>, or the error between the observed value and the fitted value</li>
</ol>
<p>We obtained these values and other values using the <code>get_regression_points()</code> function from the <code>moderndive</code> package. This time, however, we add an argument setting <code>ID = "country"</code>, which uses the variable <code>country</code> in <code>gapminder2022</code> as an <em>identification variable</em> in the output. This will help contextualize our analysis by matching values to countries.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_points</span>(life_exp_model, <span class="at">ID =</span> <span class="st">"country"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-model2-residuals" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model2-residuals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;27.8: Regression points (Sample of 6 out of 142 countries)
</figcaption>
<div aria-describedby="tbl-model2-residuals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">country</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">life_exp</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">continent</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">life_exp_hat</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">residual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: right;">53.6</td>
<td style="text-align: left;">Asia</td>
<td style="text-align: right;">75.0</td>
<td style="text-align: right;">-21.300</td>
</tr>
<tr class="even">
<td style="text-align: left;">Albania</td>
<td style="text-align: right;">79.5</td>
<td style="text-align: left;">Europe</td>
<td style="text-align: right;">79.9</td>
<td style="text-align: right;">-0.438</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Algeria</td>
<td style="text-align: right;">78.0</td>
<td style="text-align: left;">Africa</td>
<td style="text-align: right;">66.3</td>
<td style="text-align: right;">11.720</td>
</tr>
<tr class="even">
<td style="text-align: left;">Angola</td>
<td style="text-align: right;">62.1</td>
<td style="text-align: left;">Africa</td>
<td style="text-align: right;">66.3</td>
<td style="text-align: right;">-4.200</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Argentina</td>
<td style="text-align: right;">78.3</td>
<td style="text-align: left;">South America</td>
<td style="text-align: right;">75.2</td>
<td style="text-align: right;">3.083</td>
</tr>
<tr class="even">
<td style="text-align: left;">Barbados</td>
<td style="text-align: right;">78.5</td>
<td style="text-align: left;">North America</td>
<td style="text-align: right;">76.3</td>
<td style="text-align: right;">2.255</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Observe in Table <a href="#tbl-model2-residuals" class="quarto-xref">Table&nbsp;<span>27.8</span></a> that <code>life_exp_hat</code> contains the fitted values <span class="math inline">\(\widehat{y}\)</span> = <span class="math inline">\(\widehat{\text{life exp}}\)</span>. If you look closely, there are only 5 possible values for <code>life_exp_hat</code>. These correspond to the five mean life expectancies for the 5 continents that we displayed in Table <a href="#tbl-continent-mean-life-expectancies" class="quarto-xref">Table&nbsp;<span>27.7</span></a> and computed using the regression coefficient values.</p>
<p>The <code>residual</code> column is simply <span class="math inline">\(y - \widehat{y}\)</span> = <code>life_exp - life_exp_hat</code>. These values can be interpreted as the deviation of a country’s life expectancy from its continent’s average life expectancy. For example, observe the first row of Table <a href="#tbl-model2-residuals" class="quarto-xref">Table&nbsp;<span>27.8</span></a> corresponding to Afghanistan. The residual of <span class="math inline">\(y - \widehat{y} = 53.6 - 74.95 = -21.4\)</span> refers to Afghanistan’s life expectancy being 21.4 years lower than the mean life expectancy of all Asian countries. This is partly explained by the years of war that country has suffered.</p>
</section>
</section>
<section id="sec-reg-related-topics" class="level2" data-number="27.4">
<h2 data-number="27.4" class="anchored" data-anchor-id="sec-reg-related-topics"><span class="header-section-number">27.4</span> Related topics</h2>
<section id="sec-correlation-is-not-causation" class="level3" data-number="27.4.1">
<h3 data-number="27.4.1" class="anchored" data-anchor-id="sec-correlation-is-not-causation"><span class="header-section-number">27.4.1</span> Correlation is not necessarily causation</h3>
<p>Throughout this chapter we have been cautious when interpreting regression slope coefficients. We always discussed the “associated” effect of an explanatory variable <span class="math inline">\(x\)</span> on an outcome variable <span class="math inline">\(y\)</span>. For example, our statement from Subsection <a href="#sec-model1table" class="quarto-xref"><span>Section 27.2.2</span></a> that “for every increase of 1 unit in <code>life_exp</code>, there is an <em>associated</em> decrease of on average 0.137 units of <code>fert_rate</code>.” We include the term “associated” to be extra careful not to suggest we are making a <em>causal</em> statement. So while <code>life_exp</code> is negatively correlated with <code>fert_rate</code>, we can’t necessarily make any statements about life expectancy’s direct causal effect on fertility rates without more information.</p>
<p>Here is another example depicted in Figure <a href="#fig-moderndive-figure-causal-graph-2" class="quarto-xref">Figure&nbsp;<span>27.9</span></a>: a not-so-great medical doctor goes through medical records and finds that patients who slept with their shoes on tended to wake up more with headaches. So this doctor declares, “Sleeping with shoes on causes headaches!”</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-moderndive-figure-causal-graph-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-moderndive-figure-causal-graph-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/shutterstock/shoes_headache.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-moderndive-figure-causal-graph-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27.9: Does sleeping with shoes on cause headaches?
</figcaption>
</figure>
</div>
</div>
</div>
<p>However, there is a good chance that if someone is sleeping with their shoes on, it is potentially because they are intoxicated from alcohol. Furthermore, higher levels of drinking leads to more hangovers, and hence more headaches. The amount of alcohol consumption here is what’s known as a <em>confounding/lurking</em> variable. It “lurks” behind the scenes, confounding the causal relationship (if any) of “sleeping with shoes on” with “waking up with a headache.” We can summarize this in Figure <a href="#fig-moderndive-figure-causal-graph" class="quarto-xref">Figure&nbsp;<span>27.10</span></a> with a <em>causal graph</em> where Y is a <em>response</em> variable and X is a <em>treatment</em> variable whose causal effect we are interested in. </p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-moderndive-figure-causal-graph" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-moderndive-figure-causal-graph-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/flowcharts/flowchart.009-cropped.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:30.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-moderndive-figure-causal-graph-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27.10: Causal graph.
</figcaption>
</figure>
</div>
</div>
</div>
<p>To study the relationship between Y and X, we could use a regression model where the outcome variable is set to Y and the explanatory variable is set to be X, as you’ve been doing throughout this chapter. However, Figure <a href="#fig-moderndive-figure-causal-graph" class="quarto-xref">Figure&nbsp;<span>27.10</span></a> also includes a third variable with arrows pointing at both X and Y:</p>
<ul>
<li>Z is a <em>confounding</em> variable that affects both X and Y, thereby “confounding” their relationship. Here the confounding variable is alcohol.</li>
</ul>
<p>Alcohol will cause people to be both more likely to sleep with their shoes on as well as be more likely to wake up with a headache. Thus any regression model of the relationship between X and Y should also use Z as an explanatory variable. In other words, our doctor needs to take into account who had been drinking the night before. In the next chapter, we’ll start covering multiple regression models that allow us to incorporate more than one variable in our regression models.</p>
<p>Establishing causation is a tricky problem and frequently takes either carefully designed experiments or methods to control for the effects of confounding variables. Both these approaches attempt, as best they can, either to take all possible confounding variables into account or negate their impact. This allows researchers to focus only on the relationship of interest: the relationship between the outcome variable Y and the treatment variable X.</p>
<p>As you read news stories, be careful not to fall into the trap of thinking that correlation necessarily implies causation. Check out the <a href="http://www.tylervigen.com/spurious-correlations">Spurious Correlations</a> website for some comical examples of variables that are correlated, but are not causally related.</p>
<p>Coming back to our UN member states data, a confounding variable could be the level of economic development of a country. This could affect both life expectancy and fertility rates. A proxy for looking at the level of economic development could be the Human Development Index (HDI). It measures a country’s average achievements in three basic aspects of human development: health (life expectancy), education (mean and expected years of schooling), and standard of living (gross national income per capita). This is stored in the <code>hdi_2022</code> column of <code>un_member_states_2024</code>. We explore its relationship with life expectancy and fertility rates:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> un_member_states_2024, </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> hdi_2022, <span class="at">y =</span> life_expectancy_2022)) <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Human Development Index (HDI)"</span>, <span class="at">y =</span> <span class="st">"Life Expectancy"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="26_module_9_application_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> un_member_states_2024, </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> hdi_2022, <span class="at">y =</span> fertility_rate_2022)) <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Human Development Index (HDI)"</span>, <span class="at">y =</span> <span class="st">"Fertility Rate"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="26_module_9_application_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>un_member_states_2024 <span class="sc">|&gt;</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_correlation</span>(life_expectancy_2022 <span class="sc">~</span> hdi_2022, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
    cor
  &lt;dbl&gt;
1 0.889</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>un_member_states_2024 <span class="sc">|&gt;</span> </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_correlation</span>(fertility_rate_2022 <span class="sc">~</span> hdi_2022, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
     cor
   &lt;dbl&gt;
1 -0.849</code></pre>
</div>
</div>
<p>Looking at both of the scatterplots above, we see a strong positive linear relationship between the Human Development Index (HDI) and life expectancy, as well as a strong negative correlation between the Human Development Index (HDI) and fertility rates. The correlation coefficients between the Human Development Index (HDI) and life expectancy, as well as the Human Development Index (HDI) and fertility rates, are also given. These findings as well as some additional understanding of socioeconomic factors suggest that the Human Development Index (HDI) is a confounding variable in the relationship between life expectancy and fertility rates.</p>
</section>
<section id="sec-leastsquares" class="level3" data-number="27.4.2">
<h3 data-number="27.4.2" class="anchored" data-anchor-id="sec-leastsquares"><span class="header-section-number">27.4.2</span> Best-fitting line</h3>
<p>Regression lines are also known as “best-fitting” lines. But what do we mean by “best”? We unpack the criteria that is used in regression to determine “best.” Recall Figure <a href="#fig-numxplot4" class="quarto-xref">Figure&nbsp;<span>27.4</span></a>, where for Bosnia and Herzegovina we marked the <em>observed value</em> <span class="math inline">\(y\)</span> with a circle, the <em>fitted value</em> <span class="math inline">\(\widehat{y}\)</span> with a square, and the <em>residual</em> <span class="math inline">\(y - \widehat{y}\)</span> with an arrow. We re-display Figure <a href="#fig-numxplot4" class="quarto-xref">Figure&nbsp;<span>27.4</span></a> in the top-left plot of Figure <a href="#fig-best-fitting-line" class="quarto-xref">Figure&nbsp;<span>27.11</span></a> in addition to three more arbitrarily chosen countries:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-best-fitting-line" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-best-fitting-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="26_module_9_application_files/figure-html/fig-best-fitting-line-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-best-fitting-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27.11: Example of observed value, fitted value, and residual.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The four plots refer to:</p>
<ol type="1">
<li>The country of Bosnia and Herzegovina had a life expectancy <span class="math inline">\(x = 77.98\)</span> and fertility rate <span class="math inline">\(y = 1.3\)</span>. The residual in this case is <span class="math inline">\(1.3 - 1.894 = -0.594\)</span>, which we mark with an blue arrow in the top-left plot.</li>
<li>The addition of Chad, which had a life expectancy <span class="math inline">\(x = 59.15\)</span> and fertility rate <span class="math inline">\(y = 6\)</span>. The residual in this case is <span class="math inline">\(6 - 4.479 = 1.521\)</span>, which we mark with a new blue arrow in the top-right plot.</li>
<li>The addition of India, which had a life expectancy <span class="math inline">\(x = 67.22\)</span> and fertility rate <span class="math inline">\(y = 2\)</span>. The residual in this case is <span class="math inline">\(2 - 3.371 = -1.371\)</span>, which we mark with a new blue arrow in the bottom-left plot.</li>
<li>The addition of the Solomon Islands, which had a life expectancy <span class="math inline">\(x = 76.7\)</span> and fertility rate <span class="math inline">\(y = 3.8\)</span>. The residual in this case is <span class="math inline">\(3.8 - 2.069 = 1.731\)</span>, which we mark with a new blue arrow in the bottom-right plot.</li>
</ol>
<p>Now say we repeated this process of computing residuals for all 181 countries with complete information, then we squared all the residuals, and then we summed them. We call this quantity the <em>sum of squared residuals</em>; it is a measure of the <em>lack of fit</em> of a model. Larger values of the sum of squared residuals indicate a bigger lack of fit. This corresponds to a worse-fitting model.</p>
<p>If the regression line fits all the points perfectly, then the sum of squared residuals is 0. This is because if the regression line fits all the points perfectly, then the fitted value <span class="math inline">\(\widehat{y}\)</span> equals the observed value <span class="math inline">\(y\)</span> in all cases, and hence the residual <span class="math inline">\(y - \widehat{y}\)</span> = 0 in all cases, and the sum of even a large number of 0’s is still 0.</p>
<p>Furthermore, of all possible lines we can draw through the cloud of 181 points, the regression line minimizes this value. In other words, the regression and its corresponding fitted values <span class="math inline">\(\widehat{y}\)</span> minimizes the sum of the squared residuals:</p>
<p><span class="math display">\[
\sum_{i=1}^{n}(y_i - \widehat{y}_i)^2
\]</span></p>
<p>We use our data-wrangling tools to compute the sum of squared residuals exactly:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit regression model and regression points</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>demographics_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(fert_rate <span class="sc">~</span> life_exp, <span class="at">data =</span> UN_data_m9)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>regression_points <span class="ot">&lt;-</span> <span class="fu">get_regression_points</span>(demographics_model)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute sum of squared residuals</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>regression_points <span class="sc">|&gt;</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">squared_residuals =</span> residual<span class="sc">^</span><span class="dv">2</span>) <span class="sc">|&gt;</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">sum_of_squared_residuals =</span> <span class="fu">sum</span>(squared_residuals))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 81.3</code></pre>
</div>
</div>
<p>Any other straight line drawn in the figure would yield a sum of squared residuals greater than 81.265. This is a mathematically guaranteed fact that you can prove using calculus and linear algebra. That’s why alternative names for the linear regression line are the <em>best-fitting line</em> and the <em>least-squares line</em>.</p>
<p>Why do we square the residuals (i.e., the arrow lengths)? So that both positive and negative deviations of the same amount are treated equally. (That being said, while taking the absolute value of the residuals would also treat both positive and negative deviations of the same amount equally, squaring the residuals is used for reasons related to calculus: taking derivatives and minimizing functions. To learn more we suggest you consult a textbook on mathematical statistics.)</p>
</section>
<section id="sec-underthehood" class="level3" data-number="27.4.3">
<h3 data-number="27.4.3" class="anchored" data-anchor-id="sec-underthehood"><span class="header-section-number">27.4.3</span> get_regression_x() functions</h3>
<p>Recall in this chapter we introduced a wrapper function from the <code>moderndive</code> package:</p>
<ul>
<li><code>get_regression_points()</code> that returns point-by-point information from a regression model in Subsection <a href="#sec-model1points" class="quarto-xref"><span>Section 27.2.3</span></a>.</li>
</ul>
<p>What is going on behind the scenes with the <!-- `get_regression_table()` and --> <code>get_regression_points()</code> function? We mentioned in Subsection <a href="#sec-model1table" class="quarto-xref"><span>Section 27.2.2</span></a> that this was an example of a <em>wrapper function</em>. Such functions take other pre-existing functions and “wrap” them into single functions that hide the user from their inner workings. This way all the user needs to worry about is what the inputs look like and what the outputs look like. In this subsection, we’ll “get under the hood” of these functions and see how the “engine” of these wrapper functions works.</p>
<p>The <code>get_regression_points()</code> function is a wrapper function, returning information about the individual points involved in a regression model like the fitted values, observed values, and the residuals. <code>get_regression_points()</code> uses the <code>augment()</code> function in the <a href="https://broom.tidyverse.org/"><code>broom</code> package</a> <!-- instead of the `tidy()` function as with `get_regression_table()` --> to produce the data shown in Table <a href="#tbl-regpoints-augment" class="quarto-xref">Table&nbsp;<span>27.9</span></a>. Additionally, it uses <code>clean_names()</code> from the <a href="https://github.com/sfirke/janitor"><code>janitor</code> package</a> <span class="citation" data-cites="R-janitor">[@R-janitor]</span> to clean up the variable names.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>demographics_model <span class="sc">|&gt;</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>() <span class="sc">|&gt;</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_if</span>(is.numeric, round, <span class="at">digits =</span> <span class="dv">3</span>) <span class="sc">|&gt;</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>() <span class="sc">|&gt;</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(<span class="st">"std_resid"</span>, <span class="st">"hat"</span>, <span class="st">"sigma"</span>, <span class="st">"cooksd"</span>, <span class="st">"std_resid"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-regpoints-augment" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-regpoints-augment-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;27.9: Regression points using augment() from broom package
</figcaption>
<div aria-describedby="tbl-regpoints-augment-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">fert_rate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">life_exp</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">fitted</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">resid</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">4.3</td>
<td style="text-align: right;">53.6</td>
<td style="text-align: right;">5.23</td>
<td style="text-align: right;">-0.934</td>
</tr>
<tr class="even">
<td style="text-align: right;">1.4</td>
<td style="text-align: right;">79.5</td>
<td style="text-align: right;">1.69</td>
<td style="text-align: right;">-0.289</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2.7</td>
<td style="text-align: right;">78.0</td>
<td style="text-align: right;">1.89</td>
<td style="text-align: right;">0.813</td>
</tr>
<tr class="even">
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">62.1</td>
<td style="text-align: right;">4.07</td>
<td style="text-align: right;">0.928</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1.6</td>
<td style="text-align: right;">77.8</td>
<td style="text-align: right;">1.92</td>
<td style="text-align: right;">-0.318</td>
</tr>
<tr class="even">
<td style="text-align: right;">1.9</td>
<td style="text-align: right;">78.3</td>
<td style="text-align: right;">1.85</td>
<td style="text-align: right;">0.052</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1.6</td>
<td style="text-align: right;">76.1</td>
<td style="text-align: right;">2.15</td>
<td style="text-align: right;">-0.548</td>
</tr>
<tr class="even">
<td style="text-align: right;">1.6</td>
<td style="text-align: right;">83.1</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: right;">0.408</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1.5</td>
<td style="text-align: right;">82.3</td>
<td style="text-align: right;">1.30</td>
<td style="text-align: right;">0.195</td>
</tr>
<tr class="even">
<td style="text-align: right;">1.6</td>
<td style="text-align: right;">74.2</td>
<td style="text-align: right;">2.42</td>
<td style="text-align: right;">-0.819</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>In this case, it outputs only the variables of interest to students learning regression: the outcome variable <span class="math inline">\(y\)</span> (<code>fert_rate</code>), all explanatory/predictor variables (<code>life_exp</code>), all resulting <code>fitted</code> values <span class="math inline">\(\hat{y}\)</span> used by applying the equation of the regression line to <code>life_exp</code>, and the <code>resid</code>ual <span class="math inline">\(y - \hat{y}\)</span>.</p>
<p>If you are even more curious about how these and other wrapper functions work, take a look at the source code for these functions on <a href="https://github.com/moderndive/moderndive/blob/master/R/regression_functions.R">GitHub</a>.</p>
</section>
</section>
<section id="sec-reg-conclusion" class="level2" data-number="27.5">
<h2 data-number="27.5" class="anchored" data-anchor-id="sec-reg-conclusion"><span class="header-section-number">27.5</span> Conclusion</h2>
<p>In this chapter, you’ve studied the term <em>basic regression</em>, where you fit models that only have one explanatory variable. In the next module, we’ll study <em>multiple regression</em>, where our regression models can now have more than one explanatory variable! In particular, we’ll consider two scenarios: regression models with one numerical and one categorical explanatory variable and regression models with two numerical explanatory variables. This will allow you to construct more sophisticated and more powerful models, all in the hopes of better explaining your outcome variable <span class="math inline">\(y\)</span>.</p>
</section>
<section id="references" class="level2" data-number="27.6">
<h2 data-number="27.6" class="anchored" data-anchor-id="references"><span class="header-section-number">27.6</span> References</h2>
<p>Grolemund, G., &amp; Wickham, H. (2017). <em>R for Data Science</em> (1st edition). O’Reilly Media.https://r4ds.had.co.nz/.</p>
<p>James, G., Witten, D., Hastie, T., &amp; Tibshirani, R. (2017). <em>An Introduction to Statistical Learning: With Applications in R</em>. Springer</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./25_module_9_understanding.html" class="pagination-link" aria-label="M9U: Linear Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">M9U: Linear Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./27_module_9_connection.html" class="pagination-link" aria-label="M9C: Perform a Basic Regression With Your Own Data">
        <span class="nav-page-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">M9C: Perform a Basic Regression With Your Own Data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>